mod core;
mod extended;

use super::ProtocolShelfSummary;

pub(super) type ShelfMatch = (
    &'static str,
    &'static str,
    &'static str,
    &'static [&'static str],
);

pub(super) use core::{
    arp_shelf, bgp_shelf, cassandra_shelf, coap_shelf, consul_shelf, dhcp_shelf, dhcpv6_shelf,
    dns_shelf, elasticsearch_shelf, etcd_shelf, ftp_shelf, geneve_shelf, graphql_shelf, gre_shelf,
    grpc_shelf, gtpu_shelf, http_shelf, http3_shelf, https_shelf, hy2_shelf, icmp_shelf,
    icmpv6_shelf, ipsec_shelf, jaeger_shelf, kafka_shelf, l2tp_shelf, llmnr_shelf, loki_shelf,
    mdns_shelf, memcached_shelf, mongodb_shelf, mqtt_shelf, mssql_shelf, mysql_shelf, nats_shelf,
    nbns_shelf, ndp_shelf, ntp_shelf, ospf_shelf, otlp_shelf, postgres_shelf, pptp_shelf,
    prometheus_shelf, quic_shelf, radius_shelf, redis_shelf, s3_shelf, snmp_shelf, ssdp_shelf,
    stun_shelf, syslog_shelf, tftp_shelf, tls_shelf, vxlan_shelf, websocket_shelf, wireguard_shelf,
    zookeeper_shelf,
};
pub(super) use extended::{
    amqp_shelf, imap_shelf, kerberos_shelf, ldap_shelf, pop3_shelf, rdp_shelf, rtsp_shelf,
    sip_shelf, smb_shelf, smtp_shelf, socks5_shelf, ssh_shelf,
};

pub(super) fn built_in_protocol_shelf(protocol: &str, entry: &str) -> Option<ProtocolShelfSummary> {
    let (key, label, page, entries) = match protocol {
        "dns" => dns_shelf(entry)?,
        "https" => https_shelf(entry)?,
        "http" => http_shelf(entry)?,
        "grpc" => grpc_shelf(entry)?,
        "websocket" => websocket_shelf(entry)?,
        "graphql" => graphql_shelf(entry)?,
        "s3" => s3_shelf(entry)?,
        "otlp" => otlp_shelf(entry)?,
        "prometheus" => prometheus_shelf(entry)?,
        "loki" => loki_shelf(entry)?,
        "jaeger" => jaeger_shelf(entry)?,
        "syslog" => syslog_shelf(entry)?,
        "hy2" => hy2_shelf(entry)?,
        "tls" => tls_shelf(entry)?,
        "quic" => quic_shelf(entry)?,
        "stun" => stun_shelf(entry)?,
        "coap" => coap_shelf(entry)?,
        "tftp" => tftp_shelf(entry)?,
        "ntp" => ntp_shelf(entry)?,
        "dhcp" => dhcp_shelf(entry)?,
        "dhcpv6" => dhcpv6_shelf(entry)?,
        "arp" => arp_shelf(entry)?,
        "icmp" => icmp_shelf(entry)?,
        "icmpv6" => icmpv6_shelf(entry)?,
        "ndp" => ndp_shelf(entry)?,
        "bgp" => bgp_shelf(entry)?,
        "ospf" => ospf_shelf(entry)?,
        "gre" => gre_shelf(entry)?,
        "vxlan" => vxlan_shelf(entry)?,
        "geneve" => geneve_shelf(entry)?,
        "l2tp" => l2tp_shelf(entry)?,
        "pptp" => pptp_shelf(entry)?,
        "wireguard" => wireguard_shelf(entry)?,
        "ipsec" => ipsec_shelf(entry)?,
        "mdns" => mdns_shelf(entry)?,
        "llmnr" => llmnr_shelf(entry)?,
        "nbns" => nbns_shelf(entry)?,
        "ssdp" => ssdp_shelf(entry)?,
        "mysql" => mysql_shelf(entry)?,
        "postgres" => postgres_shelf(entry)?,
        "mongodb" => mongodb_shelf(entry)?,
        "cassandra" => cassandra_shelf(entry)?,
        "mssql" => mssql_shelf(entry)?,
        "elasticsearch" => elasticsearch_shelf(entry)?,
        "etcd" => etcd_shelf(entry)?,
        "zookeeper" => zookeeper_shelf(entry)?,
        "consul" => consul_shelf(entry)?,
        "mqtt" => mqtt_shelf(entry)?,
        "kafka" => kafka_shelf(entry)?,
        "nats" => nats_shelf(entry)?,
        "memcached" => memcached_shelf(entry)?,
        "radius" => radius_shelf(entry)?,
        "gtpu" => gtpu_shelf(entry)?,
        "redis" => redis_shelf(entry)?,
        "amqp" => amqp_shelf(entry)?,
        "http3" => http3_shelf(entry)?,
        "smtp" => smtp_shelf(entry)?,
        "imap" => imap_shelf(entry)?,
        "pop3" => pop3_shelf(entry)?,
        "kerberos" => kerberos_shelf(entry)?,
        "ftp" => ftp_shelf(entry)?,
        "rtsp" => rtsp_shelf(entry)?,
        "ssh" => ssh_shelf(entry)?,
        "smb" => smb_shelf(entry)?,
        "rdp" => rdp_shelf(entry)?,
        "socks5" => socks5_shelf(entry)?,
        "sip" => sip_shelf(entry)?,
        "ldap" => ldap_shelf(entry)?,
        "snmp" => snmp_shelf(entry)?,
        _ => return None,
    };
    Some(ProtocolShelfSummary {
        key: key.to_string(),
        label: label.to_string(),
        page: page.to_string(),
        entries: entries.iter().map(|entry| (*entry).to_string()).collect(),
    })
}
