using System.Text.Json.Serialization;
using Leserpent.ControlPlane;

namespace Leserpent;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    GenerationMode = JsonSourceGenerationMode.Metadata)]
[JsonSerializable(typeof(RuntimeRegistrationRequest))]
[JsonSerializable(typeof(RuntimeDeploymentRequest))]
[JsonSerializable(typeof(RuntimeDeploymentResponse))]
[JsonSerializable(typeof(RuntimeDeploymentCompatibilityEnvelope))]
[JsonSerializable(typeof(SessionCreateRequest))]
[JsonSerializable(typeof(SessionStopRequest))]
[JsonSerializable(typeof(OrchestraExecuteRequest))]
[JsonSerializable(typeof(OrchestraRetryRequest))]
[JsonSerializable(typeof(OrchestraSessionHandoffRequest))]
[JsonSerializable(typeof(PersistedControlPlaneState))]
[JsonSerializable(typeof(ServiceCapabilities))]
[JsonSerializable(typeof(PersistenceSaveResponse))]
[JsonSerializable(typeof(PersistenceImportResponse))]
[JsonSerializable(typeof(RuntimeRegistrationResponse))]
[JsonSerializable(typeof(RuntimeSummary))]
[JsonSerializable(typeof(RuntimeSummary[]))]
[JsonSerializable(typeof(RuntimeCapabilityRefreshResponse))]
[JsonSerializable(typeof(RuntimeStatusRefreshResponse))]
[JsonSerializable(typeof(RuntimeSidecarRefreshResponse))]
[JsonSerializable(typeof(RuntimeProtocolReadingSummary))]
[JsonSerializable(typeof(FleetSummary))]
[JsonSerializable(typeof(RuntimeAttentionView))]
[JsonSerializable(typeof(FleetAttentionSummary))]
[JsonSerializable(typeof(FleetStatusRefreshResponse))]
[JsonSerializable(typeof(FleetSidecarRefreshResponse))]
[JsonSerializable(typeof(FleetCapabilityRefreshResponse))]
[JsonSerializable(typeof(FleetRefreshAllResponse))]
[JsonSerializable(typeof(SessionSummary))]
[JsonSerializable(typeof(SessionSummary[]))]
[JsonSerializable(typeof(OrchestraRuntimePlanResponse))]
[JsonSerializable(typeof(OrchestraExecutionResponse))]
[JsonSerializable(typeof(OrchestraRunSummary))]
[JsonSerializable(typeof(OrchestraRunSummary[]))]
[JsonSerializable(typeof(OrchestraRunEvent[]))]
[JsonSerializable(typeof(OrchestraSessionHandoffResponse))]
[JsonSerializable(typeof(OrchestraFleetBoardResponse))]
[JsonSerializable(typeof(OrchestraExecutionStepResult[]))]
[JsonSerializable(typeof(ApiErrorResponse))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(RuntimeCollectionResponse))]
[JsonSerializable(typeof(FleetSummaryResponse))]
[JsonSerializable(typeof(FleetAttentionListResponse))]
[JsonSerializable(typeof(FleetAttentionSummaryResponse))]
[JsonSerializable(typeof(FleetRefreshAllEnvelope))]
[JsonSerializable(typeof(FleetCapabilityRefreshEnvelope))]
[JsonSerializable(typeof(FleetSidecarRefreshEnvelope))]
[JsonSerializable(typeof(FleetStatusRefreshEnvelope))]
[JsonSerializable(typeof(SessionCollectionResponse))]
[JsonSerializable(typeof(OrchestraRunCollectionResponse))]
[JsonSerializable(typeof(OrchestraRunEventsResponse))]
[JsonSerializable(typeof(OrchestraRunAcceptedResponse))]
[JsonSerializable(typeof(RuntimeDeleteResponse))]
[JsonSerializable(typeof(RuntimeBulkDeleteResponse))]
[JsonSerializable(typeof(OrchestraRevisionPayload))]
internal sealed partial class LeserpentJsonContext : JsonSerializerContext;
