use super::{
    Cli, annotate_export_trust, dsl_fixture_path, push_synthetic_missing_stage_finding,
    run_binding_demo,
};
use gewyvern::dsl::compile_file;

#[test]
fn failure_mode_label_classifies_database_directory_quic_tls_http3_and_hy2_families() {
    assert_eq!(
        crate::failure_mode_label("attention", "database_error_handling", "receive_error", &[],),
        "semantic_error"
    );
    assert_eq!(
        crate::failure_mode_label("attention", "directory_write", "receive_modify_denied", &[],),
        "server_denied"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "proxy_negotiation",
            "receive_connect_denied",
            &[],
        ),
        "server_denied"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "proxy_tunnel_establishment",
            "receive_connect_denied",
            &[],
        ),
        "server_denied"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "proxy_authentication",
            "receive_auth_required",
            &[],
        ),
        "server_denied"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "management_query",
            "receive_authorization_failure_report",
            &[],
        ),
        "server_denied"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "quic_handshake",
            "send_initial->receive_handshake",
            &[],
        ),
        "setup_incomplete"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "remote_access_session",
            "connect->receive_server_banner",
            &["transport_io".into()],
        ),
        "setup_incomplete"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "remote_access_session",
            "receive_server_banner->send_key_exchange_init",
            &["transport_io".into()],
        ),
        "not_sent"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "authentication_exchange",
            "connect->receive_banner",
            &["transport_io".into()],
        ),
        "setup_incomplete"
    );
    assert_eq!(
        crate::failure_detail_label("attention", "directory_write", "receive_modify_denied", &[],),
        "access_denied"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "proxy_negotiation",
            "receive_connect_denied",
            &[],
        ),
        "access_denied"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "proxy_tunnel_establishment",
            "receive_connect_denied",
            &[],
        ),
        "access_denied"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "proxy_authentication",
            "receive_auth_required",
            &[],
        ),
        "auth_required"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "management_query",
            "receive_authorization_failure_report",
            &[],
        ),
        "access_denied"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "proxy_negotiation",
            "send_connect_request->receive_connect_success",
            &["transport_io".into()],
        ),
        "request_sent_no_reply"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "proxy_tunnel_establishment",
            "send_connect_request->receive_connect_established",
            &["transport_io".into()],
        ),
        "request_sent_no_reply"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "quic_handshake",
            "send_initial->receive_handshake",
            &[],
        ),
        "handshake_incomplete"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "remote_access_session",
            "connect->receive_server_banner",
            &["transport_io".into()],
        ),
        "handshake_incomplete"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "remote_access_session",
            "receive_server_banner->send_key_exchange_init",
            &["transport_io".into()],
        ),
        "followup_not_sent"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "authentication_exchange",
            "connect->receive_banner",
            &["transport_io".into()],
        ),
        "handshake_incomplete"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "authentication_exchange",
            "receive_password_required->send_auth_pass",
            &["transport_io".into()],
        ),
        "not_sent"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "authentication_exchange",
            "receive_password_required->send_auth_pass",
            &["transport_io".into()],
        ),
        "followup_not_sent"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "authentication_exchange",
            "send_auth_pass->receive_auth_ok",
            &["transport_io".into()],
        ),
        "no_response"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "authentication_exchange",
            "send_auth_pass->receive_auth_ok",
            &["transport_io".into()],
        ),
        "request_sent_no_reply"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "file_transfer_session",
            "send_list->receive_transfer_open",
            &["transport_io".into()],
        ),
        "no_response"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "file_transfer_session",
            "send_port->receive_port_ready",
            &["transport_io".into()],
        ),
        "request_sent_no_reply"
    );
    assert_eq!(
        crate::failure_mode_label(
            "attention",
            "file_transfer_session",
            "send_port->receive_port_ready",
            &["transport_io".into()],
        ),
        "no_response"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "file_transfer_session",
            "send_list->receive_transfer_open",
            &["transport_io".into()],
        ),
        "request_sent_no_reply"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "tls_handshake",
            "connect->establish",
            &["route_io".into()],
        ),
        "route_or_connect_blocked"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "tls_handshake",
            "send_client_hello->receive_server_hello",
            &[],
        ),
        "handshake_incomplete"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "http3_request_response",
            "send_request_stream->receive_response_stream",
            &["transport_io".into()],
        ),
        "request_sent_no_reply"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "proxy_authentication",
            "send_auth_request_stream->receive_auth_ok_stream",
            &["transport_io".into()],
        ),
        "request_sent_no_reply"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "proxy_udp_relay",
            "send_udp_relay_datagram->receive_udp_relay_datagram",
            &["transport_io".into()],
        ),
        "request_sent_no_reply"
    );
    assert_eq!(
        crate::failure_detail_label(
            "attention",
            "proxy_tcp_relay",
            "send_tcp_request_stream->receive_tcp_response_stream",
            &["transport_io".into()],
        ),
        "request_sent_no_reply"
    );
}

#[test]
fn failure_confidence_and_basis_distinguish_direct_and_inferred_failures() {
    assert_eq!(
        crate::failure_basis_label(
            "attention",
            "proxy_authentication",
            "receive_auth_required",
            &[],
        ),
        "direct_protocol_signal"
    );
    assert_eq!(
        crate::failure_basis_label(
            "attention",
            "management_query",
            "receive_authorization_failure_report",
            &[],
        ),
        "direct_protocol_signal"
    );
    assert_eq!(
        crate::failure_confidence_label(
            "attention",
            "proxy_authentication",
            "receive_auth_required",
            &[],
        ),
        "high"
    );
    assert_eq!(
        crate::failure_confidence_label(
            "attention",
            "management_query",
            "receive_authorization_failure_report",
            &[],
        ),
        "high"
    );
    assert_eq!(
        crate::failure_basis_label(
            "attention",
            "http3_request_response",
            "send_request_stream->receive_response_stream",
            &["transport_io".into()],
        ),
        "missing_transition"
    );
    assert_eq!(
        crate::failure_confidence_label(
            "attention",
            "http3_request_response",
            "send_request_stream->receive_response_stream",
            &["transport_io".into()],
        ),
        "medium"
    );
    assert_eq!(
        crate::failure_basis_label(
            "attention",
            "tls_handshake",
            "connect->establish",
            &["route_io".into()],
        ),
        "missing_transition"
    );
}

#[test]
fn process_profiles_lower_confidence_for_competing_missing_transition_hypotheses() {
    let binding = compile_file(&dsl_fixture_path("http_request_path.gewy"))
        .expect("http_request_path DSL should compile");
    let mut export = annotate_export_trust(
        run_binding_demo(binding),
        &Cli::from_args(["--demo".to_string(), "tcp".to_string()]).unwrap(),
    );
    let primary_flow = export.program_flows[0].clone();
    push_synthetic_missing_stage_finding(
        &mut export,
        &primary_flow,
        "http_request_path",
        "http_request_response",
        "receive_response",
        "receive_payload",
        "send_request->receive_response",
        "emit_payload->receive_payload",
        "transport_io",
        "synthetic missing http response",
        "tcp_packet_meta_fragment",
        "missing_signal:packet_observed",
    );

    let mut competing_flow = primary_flow.clone();
    competing_flow.id = gewyvern::flow::ProgramFlowId(primary_flow.id.0 + 5000);
    export.program_flows.push(competing_flow.clone());
    push_synthetic_missing_stage_finding(
        &mut export,
        &competing_flow,
        "http_connect_authenticated_tunnel_path",
        "proxy_authentication",
        "receive_auth_ok",
        "receive_payload",
        "send_auth_request->receive_auth_ok",
        "emit_payload->receive_payload",
        "transport_io",
        "synthetic missing proxy auth response",
        "tcp_packet_meta_fragment",
        "missing_signal:packet_observed",
    );

    let json = crate::process_network_profiles_json(&export);
    assert!(
        json.contains("\"module_kinds\":[\"http_request_response\",\"proxy_authentication\"]"),
        "json={}",
        json
    );
    assert!(
        json.contains(
            "\"missing_transitions\":[\"send_auth_request->receive_auth_ok\",\"send_request->receive_response\"]"
        ),
        "json={}",
        json
    );
    assert!(
        json.contains("\"primary_failure_confidence\":\"low\""),
        "json={}",
        json
    );
    assert!(
        json.contains("\"primary_failure_basis\":\"missing_transition\""),
        "json={}",
        json
    );
    assert!(json.contains("\"ambiguous\":true"), "json={}", json);
    assert!(json.contains("\"competing_hypotheses\":["), "json={}", json);
    assert!(
        json.contains("\"module:proxy_authentication\""),
        "json={}",
        json
    );
    assert!(
        json.contains("\"transition:send_request->receive_response\"")
            || json.contains("\"transition:send_auth_request->receive_auth_ok\""),
        "json={}",
        json
    );
}
