use super::*;

#[test]
fn summary_json_carries_smtp_rcpt_timeout_detail() {
    let binding = compile_file("/Users/Shared/chroot/dev/gewyvern/dsl/smtp_rcpt_path.gewy")
        .expect("smtp_rcpt_path DSL should compile");
    let mut export = annotate_export_trust(
        export_from_test_facts(
            binding,
            vec![
                sock_lineage_fact_for_tests(1, 82913, 53017, "postfix-client"),
                route_fact(
                    2,
                    SystemTime::UNIX_EPOCH + Duration::from_millis(20),
                    82913,
                    7,
                    SessionId(1),
                ),
                tcp_state_fact_with_ports_for_tests(3, 82913, 1, 2, 53017, 25),
                packet_fact_with_dir_and_payload_for_tests(
                    4,
                    82913,
                    0x18,
                    PacketDir::Ingress,
                    Some(53017),
                    Some(25),
                    Some(0x32),
                    Some(0x3232),
                    Some(0x32323020),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    5,
                    82913,
                    0x18,
                    PacketDir::Egress,
                    Some(53017),
                    Some(25),
                    Some(0x45),
                    Some(0x4548),
                    Some(0x45484c4f),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    6,
                    82913,
                    0x18,
                    PacketDir::Ingress,
                    Some(53017),
                    Some(25),
                    Some(0x32),
                    Some(0x3235),
                    Some(0x32353020),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    7,
                    82913,
                    0x18,
                    PacketDir::Egress,
                    Some(53017),
                    Some(25),
                    Some(0x41),
                    Some(0x4155),
                    Some(0x41555448),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    8,
                    82913,
                    0x18,
                    PacketDir::Ingress,
                    Some(53017),
                    Some(25),
                    Some(0x32),
                    Some(0x3233),
                    Some(0x32333520),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    9,
                    82913,
                    0x18,
                    PacketDir::Egress,
                    Some(53017),
                    Some(25),
                    Some(0x4d),
                    Some(0x4d41),
                    Some(0x4d41494c),
                ),
                packet_fact_with_dir_and_payload_bytes_for_tests(
                    10,
                    82913,
                    0x18,
                    PacketDir::Ingress,
                    Some(53017),
                    Some(25),
                    &[
                        (0, 0x32),
                        (1, 0x35),
                        (2, 0x30),
                        (3, 0x20),
                        (4, 0x32),
                        (5, 0x2e),
                        (6, 0x31),
                        (7, 0x2e),
                    ],
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    11,
                    82913,
                    0x18,
                    PacketDir::Egress,
                    Some(53017),
                    Some(25),
                    Some(0x52),
                    Some(0x5243),
                    Some(0x52435054),
                ),
            ],
        ),
        &Cli::from_args(["--demo".to_string(), "tcp".to_string()]).unwrap(),
    );
    let flow = export.program_flows[0].clone();
    push_synthetic_missing_stage_finding(
        &mut export,
        &flow,
        "smtp_rcpt_path",
        "mail_session",
        "receive_rcpt_ok",
        "receive_payload",
        "send_rcpt_to->receive_rcpt_ok",
        "emit_payload->receive_payload",
        "transport_io",
        "synthetic missing smtp rcpt ok",
        "tcp_packet_meta_fragment",
        "missing_signal:packet_observed",
    );
    let json = summary_json("dsl_demo", &export);
    assert!(json.contains("\"primary_module_kind\":\"mail_session\""));
    assert!(json.contains("\"primary_failure_mode\":\"no_response\""));
    assert!(json.contains("\"primary_failure_detail\":\"request_sent_no_reply\""));
    assert!(json.contains("\"primary_failure_confidence\":\"medium\""));
    assert!(json.contains("\"primary_failure_basis\":\"missing_transition\""));
}

#[test]
fn summary_json_carries_smtp_rcpt_denied_detail() {
    let binding = compile_file("/Users/Shared/chroot/dev/gewyvern/dsl/smtp_rcpt_denied_path.gewy")
        .expect("smtp_rcpt_denied_path DSL should compile");
    let export = annotate_export_trust(
        export_from_test_facts(
            binding,
            vec![
                sock_lineage_fact_for_tests(1, 82916, 53022, "postfix-client"),
                route_fact(
                    2,
                    SystemTime::UNIX_EPOCH + Duration::from_millis(20),
                    82916,
                    7,
                    SessionId(1),
                ),
                tcp_state_fact_with_ports_for_tests(3, 82916, 1, 2, 53022, 25),
                packet_fact_with_dir_and_payload_for_tests(
                    4,
                    82916,
                    0x18,
                    PacketDir::Ingress,
                    Some(53022),
                    Some(25),
                    Some(0x32),
                    Some(0x3232),
                    Some(0x32323020),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    5,
                    82916,
                    0x18,
                    PacketDir::Egress,
                    Some(53022),
                    Some(25),
                    Some(0x45),
                    Some(0x4548),
                    Some(0x45484c4f),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    6,
                    82916,
                    0x18,
                    PacketDir::Ingress,
                    Some(53022),
                    Some(25),
                    Some(0x32),
                    Some(0x3235),
                    Some(0x32353020),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    7,
                    82916,
                    0x18,
                    PacketDir::Egress,
                    Some(53022),
                    Some(25),
                    Some(0x41),
                    Some(0x4155),
                    Some(0x41555448),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    8,
                    82916,
                    0x18,
                    PacketDir::Ingress,
                    Some(53022),
                    Some(25),
                    Some(0x32),
                    Some(0x3233),
                    Some(0x32333520),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    9,
                    82916,
                    0x18,
                    PacketDir::Egress,
                    Some(53022),
                    Some(25),
                    Some(0x4d),
                    Some(0x4d41),
                    Some(0x4d41494c),
                ),
                packet_fact_with_dir_and_payload_bytes_for_tests(
                    10,
                    82916,
                    0x18,
                    PacketDir::Ingress,
                    Some(53022),
                    Some(25),
                    &[
                        (0, 0x32),
                        (1, 0x35),
                        (2, 0x30),
                        (3, 0x20),
                        (4, 0x32),
                        (5, 0x2e),
                        (6, 0x31),
                        (7, 0x2e),
                    ],
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    11,
                    82916,
                    0x18,
                    PacketDir::Egress,
                    Some(53022),
                    Some(25),
                    Some(0x52),
                    Some(0x5243),
                    Some(0x52435054),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    12,
                    82916,
                    0x18,
                    PacketDir::Ingress,
                    Some(53022),
                    Some(25),
                    Some(0x35),
                    Some(0x3535),
                    Some(0x35353020),
                ),
            ],
        ),
        &Cli::from_args(["--demo".to_string(), "tcp".to_string()]).unwrap(),
    );
    let json = summary_json("dsl_demo", &export);
    assert!(json.contains("\"primary_module_kind\":\"mail_session\""));
    assert!(json.contains("\"primary_failure_mode\":\"server_denied\""));
    assert!(json.contains("\"primary_failure_detail\":\"access_denied\""));
    assert!(json.contains("\"primary_failure_confidence\":\"high\""));
    assert!(json.contains("\"primary_failure_basis\":\"direct_protocol_signal\""));
}

#[test]
fn summary_json_carries_smtp_data_timeout_detail() {
    let binding = compile_file("/Users/Shared/chroot/dev/gewyvern/dsl/smtp_data_path.gewy")
        .expect("smtp_data_path DSL should compile");
    let mut export = annotate_export_trust(
        export_from_test_facts(
            binding,
            vec![
                sock_lineage_fact_for_tests(1, 82914, 53019, "postfix-client"),
                route_fact(
                    2,
                    SystemTime::UNIX_EPOCH + Duration::from_millis(20),
                    82914,
                    7,
                    SessionId(1),
                ),
                tcp_state_fact_with_ports_for_tests(3, 82914, 1, 2, 53019, 25),
                packet_fact_with_dir_and_payload_for_tests(
                    4,
                    82914,
                    0x18,
                    PacketDir::Ingress,
                    Some(53019),
                    Some(25),
                    Some(0x32),
                    Some(0x3232),
                    Some(0x32323020),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    5,
                    82914,
                    0x18,
                    PacketDir::Egress,
                    Some(53019),
                    Some(25),
                    Some(0x45),
                    Some(0x4548),
                    Some(0x45484c4f),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    6,
                    82914,
                    0x18,
                    PacketDir::Ingress,
                    Some(53019),
                    Some(25),
                    Some(0x32),
                    Some(0x3235),
                    Some(0x32353020),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    7,
                    82914,
                    0x18,
                    PacketDir::Egress,
                    Some(53019),
                    Some(25),
                    Some(0x41),
                    Some(0x4155),
                    Some(0x41555448),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    8,
                    82914,
                    0x18,
                    PacketDir::Ingress,
                    Some(53019),
                    Some(25),
                    Some(0x32),
                    Some(0x3233),
                    Some(0x32333520),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    9,
                    82914,
                    0x18,
                    PacketDir::Egress,
                    Some(53019),
                    Some(25),
                    Some(0x4d),
                    Some(0x4d41),
                    Some(0x4d41494c),
                ),
                packet_fact_with_dir_and_payload_bytes_for_tests(
                    10,
                    82914,
                    0x18,
                    PacketDir::Ingress,
                    Some(53019),
                    Some(25),
                    &[
                        (0, 0x32),
                        (1, 0x35),
                        (2, 0x30),
                        (3, 0x20),
                        (4, 0x32),
                        (5, 0x2e),
                        (6, 0x31),
                        (7, 0x2e),
                    ],
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    11,
                    82914,
                    0x18,
                    PacketDir::Egress,
                    Some(53019),
                    Some(25),
                    Some(0x52),
                    Some(0x5243),
                    Some(0x52435054),
                ),
                packet_fact_with_dir_and_payload_bytes_for_tests(
                    12,
                    82914,
                    0x18,
                    PacketDir::Ingress,
                    Some(53019),
                    Some(25),
                    &[
                        (0, 0x32),
                        (1, 0x35),
                        (2, 0x30),
                        (3, 0x20),
                        (4, 0x32),
                        (5, 0x2e),
                        (6, 0x31),
                        (7, 0x2e),
                        (8, 0x35),
                    ],
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    13,
                    82914,
                    0x18,
                    PacketDir::Egress,
                    Some(53019),
                    Some(25),
                    Some(0x44),
                    Some(0x4441),
                    Some(0x44415441),
                ),
                packet_fact_with_dir_and_payload_for_tests(
                    14,
                    82914,
                    0x18,
                    PacketDir::Ingress,
                    Some(53019),
                    Some(25),
                    Some(0x33),
                    Some(0x3335),
                    Some(0x33353420),
                ),
                packet_fact_with_dir_and_payload_bytes_for_tests(
                    15,
                    82914,
                    0x18,
                    PacketDir::Egress,
                    Some(53019),
                    Some(25),
                    &[(0, 0x0d), (1, 0x0a), (2, 0x2e), (3, 0x0d), (4, 0x0a)],
                ),
            ],
        ),
        &Cli::from_args(["--demo".to_string(), "tcp".to_string()]).unwrap(),
    );
    let flow = export.program_flows[0].clone();
    push_synthetic_missing_stage_finding(
        &mut export,
        &flow,
        "smtp_data_path",
        "mail_session",
        "receive_message_queued",
        "receive_payload",
        "send_message_body->receive_message_queued",
        "emit_payload->receive_payload",
        "transport_io",
        "synthetic missing smtp message queued",
        "tcp_packet_meta_fragment",
        "missing_signal:packet_observed",
    );
    let json = summary_json("dsl_demo", &export);
    assert!(json.contains("\"primary_module_kind\":\"mail_session\""));
    assert!(json.contains("\"primary_failure_mode\":\"no_response\""));
    assert!(json.contains("\"primary_failure_detail\":\"request_sent_no_reply\""));
    assert!(json.contains("\"primary_failure_confidence\":\"medium\""));
    assert!(json.contains("\"primary_failure_basis\":\"missing_transition\""));
}
