{
            vec![
                FactEnvelope {
                    id: FactId(1),
                    ts: base,
                    cpu: CpuId(0),
                    ifindex: Some(2),
                    session: SessionId(2),
                    fragment_id: "sock_lineage_fragment".into(),
                    kind: FactKind::SockLineage(SockLineageFact {
                        netns: 1,
                        sk_cookie: 166,
                        pid: 4242,
                        tid: 4242,
                        cgroup_id: 4242,
                        comm: {
                            let mut comm = [0u8; 16];
                            comm[..4].copy_from_slice(b"curl");
                            comm
                        },
                    }),
                },
                route_fact(2, base + Duration::from_millis(10), 166, 3, SessionId(2)),
                FactEnvelope {
                    id: FactId(3),
                    ts: base + Duration::from_millis(20),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "tcp_state_fragment".into(),
                    kind: FactKind::TcpState(TcpStateFact {
                        netns: 1,
                        sk_cookie: 166,
                        saddr: [0; 16],
                        daddr: [0; 16],
                        sport: 54100,
                        dport: 8080,
                        family: 2,
                        old: 1,
                        new: 2,
                    }),
                },
                FactEnvelope {
                    id: FactId(4),
                    ts: base + Duration::from_millis(30),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "tcp_state_fragment".into(),
                    kind: FactKind::TcpState(TcpStateFact {
                        netns: 1,
                        sk_cookie: 166,
                        saddr: [0; 16],
                        daddr: [0; 16],
                        sport: 54100,
                        dport: 8080,
                        family: 2,
                        old: 2,
                        new: 3,
                    }),
                },
                FactEnvelope {
                    id: FactId(5),
                    ts: base + Duration::from_millis(40),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "tcp_packet_meta_fragment".into(),
                    kind: FactKind::PacketMeta(PacketMetaFact {
                        netns: 1,
                        sk_cookie: Some(166),
                        dir: PacketDir::Egress,
                        local_port: Some(54100),
                        remote_port: Some(8080),
                        payload_byte0: Some(0x43),
                        payload_byte1: Some(0x4f),
                        payload_prefix2: Some(0x434f),
                        payload_prefix4: Some(0x434f4e4e),
                        payload_byte4: None,
                        payload_byte5: None,
                        payload_byte9: None,
                        payload_byte10: None,
                        payload_byte13: None,
                        payload_bytes: std::collections::BTreeMap::from([
                            (0u16, 0x43),
                            (1u16, 0x4f),
                            (2u16, 0x4e),
                            (3u16, 0x4e),
                        ]),
                        l3_proto: 0x0800,
                        l4_proto: 6,
                        tot_len: 110,
                        tcp_flags: 0x18,
                        seq: Some(1),
                        ack: Some(1),
                        window: Some(65535),
                    }),
                },
                FactEnvelope {
                    id: FactId(6),
                    ts: base + Duration::from_millis(50),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "tcp_packet_meta_fragment".into(),
                    kind: FactKind::PacketMeta(PacketMetaFact {
                        netns: 1,
                        sk_cookie: Some(166),
                        dir: PacketDir::Ingress,
                        local_port: Some(54100),
                        remote_port: Some(8080),
                        payload_byte0: Some(0x32),
                        payload_byte1: Some(0x30),
                        payload_prefix2: Some(0x3230),
                        payload_prefix4: Some(0x32303020),
                        payload_byte4: None,
                        payload_byte5: None,
                        payload_byte9: None,
                        payload_byte10: None,
                        payload_byte13: None,
                        payload_bytes: std::collections::BTreeMap::from([
                            (0u16, 0x32),
                            (1u16, 0x30),
                            (2u16, 0x30),
                            (3u16, 0x20),
                        ]),
                        l3_proto: 0x0800,
                        l4_proto: 6,
                        tot_len: 96,
                        tcp_flags: 0x18,
                        seq: Some(2),
                        ack: Some(2),
                        window: Some(65535),
                    }),
                },
            ]
}
