{
            vec![
                FactEnvelope {
                    id: FactId(1),
                    ts: base,
                    cpu: CpuId(0),
                    ifindex: Some(2),
                    session: SessionId(2),
                    fragment_id: "sock_lineage_fragment".into(),
                    kind: FactKind::SockLineage(SockLineageFact {
                        netns: 1,
                        sk_cookie: 155,
                        pid: 4242,
                        tid: 4242,
                        cgroup_id: 4242,
                        comm: {
                            let mut comm = [0u8; 16];
                            comm[..4].copy_from_slice(b"curl");
                            comm
                        },
                    }),
                },
                route_fact(2, base + Duration::from_millis(10), 155, 3, SessionId(2)),
                FactEnvelope {
                    id: FactId(3),
                    ts: base + Duration::from_millis(20),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "tcp_state_fragment".into(),
                    kind: FactKind::TcpState(TcpStateFact {
                        netns: 1,
                        sk_cookie: 155,
                        saddr: [0; 16],
                        daddr: [0; 16],
                        sport: 54000,
                        dport: 1080,
                        family: 2,
                        old: 1,
                        new: 2,
                    }),
                },
                FactEnvelope {
                    id: FactId(4),
                    ts: base + Duration::from_millis(30),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "tcp_state_fragment".into(),
                    kind: FactKind::TcpState(TcpStateFact {
                        netns: 1,
                        sk_cookie: 155,
                        saddr: [0; 16],
                        daddr: [0; 16],
                        sport: 54000,
                        dport: 1080,
                        family: 2,
                        old: 2,
                        new: 3,
                    }),
                },
                FactEnvelope {
                    id: FactId(5),
                    ts: base + Duration::from_millis(40),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "tcp_packet_meta_fragment".into(),
                    kind: FactKind::PacketMeta(PacketMetaFact {
                        netns: 1,
                        sk_cookie: Some(155),
                        dir: PacketDir::Egress,
                        local_port: Some(54000),
                        remote_port: Some(1080),
                        payload_byte0: Some(0x05),
                        payload_byte1: Some(0x01),
                        payload_prefix2: Some(0x0501),
                        payload_prefix4: None,
                        payload_byte4: None,
                        payload_byte5: None,
                        payload_byte9: None,
                        payload_byte10: None,
                        payload_byte13: None,
                        payload_bytes: std::collections::BTreeMap::from([
                            (0u16, 0x05),
                            (1u16, 0x01),
                        ]),
                        l3_proto: 0x0800,
                        l4_proto: 6,
                        tot_len: 80,
                        tcp_flags: 0x18,
                        seq: Some(1),
                        ack: Some(1),
                        window: Some(65535),
                    }),
                },
                FactEnvelope {
                    id: FactId(6),
                    ts: base + Duration::from_millis(50),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "tcp_packet_meta_fragment".into(),
                    kind: FactKind::PacketMeta(PacketMetaFact {
                        netns: 1,
                        sk_cookie: Some(155),
                        dir: PacketDir::Ingress,
                        local_port: Some(54000),
                        remote_port: Some(1080),
                        payload_byte0: Some(0x05),
                        payload_byte1: Some(0x00),
                        payload_prefix2: Some(0x0500),
                        payload_prefix4: None,
                        payload_byte4: None,
                        payload_byte5: None,
                        payload_byte9: None,
                        payload_byte10: None,
                        payload_byte13: None,
                        payload_bytes: std::collections::BTreeMap::from([
                            (0u16, 0x05),
                            (1u16, 0x00),
                        ]),
                        l3_proto: 0x0800,
                        l4_proto: 6,
                        tot_len: 80,
                        tcp_flags: 0x18,
                        seq: Some(2),
                        ack: Some(2),
                        window: Some(65535),
                    }),
                },
                FactEnvelope {
                    id: FactId(7),
                    ts: base + Duration::from_millis(60),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "tcp_packet_meta_fragment".into(),
                    kind: FactKind::PacketMeta(PacketMetaFact {
                        netns: 1,
                        sk_cookie: Some(155),
                        dir: PacketDir::Egress,
                        local_port: Some(54000),
                        remote_port: Some(1080),
                        payload_byte0: Some(0x05),
                        payload_byte1: Some(0x01),
                        payload_prefix2: Some(0x0501),
                        payload_prefix4: Some(0x05010003),
                        payload_byte4: None,
                        payload_byte5: None,
                        payload_byte9: None,
                        payload_byte10: None,
                        payload_byte13: None,
                        payload_bytes: std::collections::BTreeMap::from([
                            (0u16, 0x05),
                            (1u16, 0x01),
                            (2u16, 0x00),
                            (3u16, 0x03),
                        ]),
                        l3_proto: 0x0800,
                        l4_proto: 6,
                        tot_len: 92,
                        tcp_flags: 0x18,
                        seq: Some(3),
                        ack: Some(3),
                        window: Some(65535),
                    }),
                },
                FactEnvelope {
                    id: FactId(8),
                    ts: base + Duration::from_millis(70),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "tcp_packet_meta_fragment".into(),
                    kind: FactKind::PacketMeta(PacketMetaFact {
                        netns: 1,
                        sk_cookie: Some(155),
                        dir: PacketDir::Ingress,
                        local_port: Some(54000),
                        remote_port: Some(1080),
                        payload_byte0: Some(0x05),
                        payload_byte1: Some(0x00),
                        payload_prefix2: Some(0x0500),
                        payload_prefix4: Some(0x05000001),
                        payload_byte4: None,
                        payload_byte5: None,
                        payload_byte9: None,
                        payload_byte10: None,
                        payload_byte13: None,
                        payload_bytes: std::collections::BTreeMap::from([
                            (0u16, 0x05),
                            (1u16, 0x00),
                            (2u16, 0x00),
                            (3u16, 0x01),
                        ]),
                        l3_proto: 0x0800,
                        l4_proto: 6,
                        tot_len: 92,
                        tcp_flags: 0x18,
                        seq: Some(4),
                        ack: Some(4),
                        window: Some(65535),
                    }),
                },
            ]
}
