{
            vec![
                FactEnvelope {
                    id: FactId(1),
                    ts: base,
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "sock_lineage_fragment".into(),
                    kind: FactKind::SockLineage(SockLineageFact {
                        netns: 1,
                        sk_cookie: 199,
                        pid: 4242,
                        tid: 4242,
                        cgroup_id: 4242,
                        comm: {
                            let mut comm = [0u8; 16];
                            comm[..8].copy_from_slice(b"hysteria");
                            comm
                        },
                    }),
                },
                route_fact(2, base + Duration::from_millis(10), 199, 3, SessionId(2)),
                FactEnvelope {
                    id: FactId(3),
                    ts: base + Duration::from_millis(20),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "udp_packet_meta_fragment".into(),
                    kind: FactKind::PacketMeta(PacketMetaFact {
                        netns: 1,
                        sk_cookie: Some(199),
                        dir: PacketDir::Egress,
                        local_port: Some(42310),
                        remote_port: Some(443),
                        payload_byte0: Some(0xc0),
                        payload_byte1: None,
                        payload_prefix2: Some(0xc300),
                        payload_prefix4: None,
                        payload_byte4: None,
                        payload_byte5: None,
                        payload_byte9: None,
                        payload_byte10: None,
                        payload_byte13: None,
                        payload_bytes: std::collections::BTreeMap::new(),
                        l3_proto: 0x0800,
                        l4_proto: 17,
                        tot_len: 1300,
                        tcp_flags: 0,
                        seq: None,
                        ack: None,
                        window: None,
                    }),
                },
                FactEnvelope {
                    id: FactId(4),
                    ts: base + Duration::from_millis(30),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "udp_packet_meta_fragment".into(),
                    kind: FactKind::QuicMeta(gewyvern::ledger::QuicMetaFact {
                        netns: 1,
                        sk_cookie: Some(199),
                        dir: PacketDir::Egress,
                        local_port: Some(42310),
                        remote_port: Some(443),
                        long_header: true,
                        packet_type: Some(QuicPacketType::Initial),
                        frame_types: vec![QuicFrameType::Crypto],
                        payload_bytes: std::collections::BTreeMap::new(),
                    }),
                },
                FactEnvelope {
                    id: FactId(5),
                    ts: base + Duration::from_millis(40),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "udp_packet_meta_fragment".into(),
                    kind: FactKind::PacketMeta(PacketMetaFact {
                        netns: 1,
                        sk_cookie: Some(199),
                        dir: PacketDir::Ingress,
                        local_port: Some(42310),
                        remote_port: Some(443),
                        payload_byte0: Some(0xe0),
                        payload_byte1: None,
                        payload_prefix2: None,
                        payload_prefix4: None,
                        payload_byte4: None,
                        payload_byte5: None,
                        payload_byte9: None,
                        payload_byte10: None,
                        payload_byte13: None,
                        payload_bytes: std::collections::BTreeMap::new(),
                        l3_proto: 0x0800,
                        l4_proto: 17,
                        tot_len: 220,
                        tcp_flags: 0,
                        seq: None,
                        ack: None,
                        window: None,
                    }),
                },
                FactEnvelope {
                    id: FactId(6),
                    ts: base + Duration::from_millis(50),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "udp_packet_meta_fragment".into(),
                    kind: FactKind::QuicMeta(gewyvern::ledger::QuicMetaFact {
                        netns: 1,
                        sk_cookie: Some(199),
                        dir: PacketDir::Ingress,
                        local_port: Some(42310),
                        remote_port: Some(443),
                        long_header: true,
                        packet_type: Some(QuicPacketType::Handshake),
                        frame_types: vec![QuicFrameType::Crypto],
                        payload_bytes: std::collections::BTreeMap::new(),
                    }),
                },
                FactEnvelope {
                    id: FactId(7),
                    ts: base + Duration::from_millis(60),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "udp_packet_meta_fragment".into(),
                    kind: FactKind::QuicMeta(gewyvern::ledger::QuicMetaFact {
                        netns: 1,
                        sk_cookie: Some(199),
                        dir: PacketDir::Egress,
                        local_port: Some(42310),
                        remote_port: Some(443),
                        long_header: false,
                        packet_type: None,
                        frame_types: vec![QuicFrameType::Stream],
                        payload_bytes: std::collections::BTreeMap::new(),
                    }),
                },
                FactEnvelope {
                    id: FactId(8),
                    ts: base + Duration::from_millis(70),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "udp_packet_meta_fragment".into(),
                    kind: FactKind::QuicMeta(gewyvern::ledger::QuicMetaFact {
                        netns: 1,
                        sk_cookie: Some(199),
                        dir: PacketDir::Ingress,
                        local_port: Some(42310),
                        remote_port: Some(443),
                        long_header: false,
                        packet_type: None,
                        frame_types: vec![QuicFrameType::Stream],
                        payload_bytes: std::collections::BTreeMap::new(),
                    }),
                },
                FactEnvelope {
                    id: FactId(9),
                    ts: base + Duration::from_millis(80),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "udp_packet_meta_fragment".into(),
                    kind: FactKind::QuicMeta(gewyvern::ledger::QuicMetaFact {
                        netns: 1,
                        sk_cookie: Some(199),
                        dir: PacketDir::Egress,
                        local_port: Some(42310),
                        remote_port: Some(443),
                        long_header: false,
                        packet_type: None,
                        frame_types: vec![QuicFrameType::Datagram],
                        payload_bytes: std::collections::BTreeMap::new(),
                    }),
                },
                FactEnvelope {
                    id: FactId(10),
                    ts: base + Duration::from_millis(90),
                    cpu: CpuId(0),
                    ifindex: Some(3),
                    session: SessionId(2),
                    fragment_id: "udp_packet_meta_fragment".into(),
                    kind: FactKind::QuicMeta(gewyvern::ledger::QuicMetaFact {
                        netns: 1,
                        sk_cookie: Some(199),
                        dir: PacketDir::Ingress,
                        local_port: Some(42310),
                        remote_port: Some(443),
                        long_header: false,
                        packet_type: None,
                        frame_types: vec![QuicFrameType::Datagram],
                        payload_bytes: std::collections::BTreeMap::new(),
                    }),
                },
            ]
}
