<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-android</TargetFramework>
    <ApplicationId>org.gewyvern.leserpent</ApplicationId>
    <ApplicationTitle>Leserpent</ApplicationTitle>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.2.0</ApplicationDisplayVersion>
    <SupportedOSPlatformVersion>23.0</SupportedOSPlatformVersion>
    <AndroidPackageFormat Condition="'$(Configuration)' == 'Release'">aab</AndroidPackageFormat>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Leserpent.MobileCore/Leserpent.MobileCore.csproj" />
  </ItemGroup>
</Project>
