use super::common::{failure, summary};
use crate::protocol_profiles::ProtocolEntrySemanticsSummary;

pub(super) fn snmp_entry_semantics(entry: &str) -> Option<ProtocolEntrySemanticsSummary> {
    match entry {
        "get" => summary(
            "snmp-read-path",
            "SNMP GET request and response reading one or more managed object values",
            Some("GetRequest PDU + Response PDU"),
            None,
            None,
            Some("protocol_entry_signal"),
        ),
        "get-next" => summary(
            "snmp-walk-path",
            "SNMP GETNEXT request and response walking adjacent managed object values",
            Some("GetNextRequest PDU + Response PDU"),
            None,
            None,
            Some("protocol_entry_signal"),
        ),
        "bulk" => summary(
            "snmp-bulk-read-path",
            "SNMP GETBULK request and response collecting a larger management table slice",
            Some("GetBulkRequest PDU + Response PDU"),
            None,
            None,
            Some("protocol_entry_signal"),
        ),
        "set" => summary(
            "snmp-write-path",
            "SNMP SET request and response changing a managed object value",
            Some("SetRequest PDU + Response PDU"),
            None,
            None,
            Some("protocol_entry_signal"),
        ),
        "trap" => summary(
            "snmp-notification-path",
            "one-way SNMP trap notification emitted from an agent toward a manager",
            Some("Trap PDU"),
            None,
            None,
            Some("protocol_entry_signal"),
        ),
        "inform" => summary(
            "snmp-acknowledged-notification-path",
            "SNMP inform notification followed by manager acknowledgement",
            Some("InformRequest PDU + Response PDU"),
            None,
            None,
            Some("protocol_entry_signal"),
        ),
        "engine-sync" => summary(
            "snmp-engine-sync-path",
            "SNMPv3 engine identifier and time synchronization before authenticated access",
            Some("SNMPv3 discovery/report exchange"),
            None,
            None,
            Some("protocol_entry_signal"),
        ),
        "trap-recv" => summary(
            "snmp-notification-receive-path",
            "SNMP trap notification received by a local management listener",
            Some("Trap PDU ingress"),
            None,
            None,
            Some("protocol_entry_signal"),
        ),
        "report" => summary(
            "snmp-report-path",
            "SNMP report response carrying protocol status or engine discovery data",
            Some("Report PDU"),
            None,
            None,
            Some("protocol_entry_signal"),
        ),
        "unauthorized" => failure(
            "authorization failure report after SNMPv3 access evaluation",
            None,
            Some("server_denied"),
            Some("access_denied"),
        ),
        "v3-auth" => summary(
            "snmpv3-authenticated-path",
            "SNMPv3 authenticated message exchange with authNoPriv security",
            Some("SNMPv3 msgFlags auth bit"),
            None,
            None,
            Some("protocol_entry_signal"),
        ),
        "v3-priv" => summary(
            "snmpv3-private-path",
            "SNMPv3 authenticated and encrypted message exchange with authPriv security",
            Some("SNMPv3 msgFlags auth+priv bits"),
            None,
            None,
            Some("protocol_entry_signal"),
        ),
        _ => None,
    }
}
