internal static class DesktopBuiltInShellCatalogs
{
    public static IReadOnlyDictionary<DesktopTextKey, string> TraditionalChinese { get; } =
        Catalog(new Dictionary<DesktopTextKey, string>
        {
            [DesktopTextKey.AboutLeserpent] = "關於 Leserpent",
            [DesktopTextKey.LearningCenter] = "學習中心...",
            [DesktopTextKey.Connection] = "連線...",
            [DesktopTextKey.Language] = "語言...",
            [DesktopTextKey.ShowLeserpent] = "顯示 Leserpent",
            [DesktopTextKey.QuitLeserpent] = "結束 Leserpent",
            [DesktopTextKey.Close] = "關閉",
            [DesktopTextKey.Cancel] = "取消",
            [DesktopTextKey.Apply] = "套用",
            [DesktopTextKey.Clear] = "清除",
            [DesktopTextKey.Open] = "開啟",
            [DesktopTextKey.Refresh] = "刷新",
            [DesktopTextKey.Manage] = "管理",
            [DesktopTextKey.RefreshAll] = "全部刷新",
            [DesktopTextKey.FollowSystem] = "跟隨系統",
            [DesktopTextKey.QuickTour] = "快速導覽",
            [DesktopTextKey.AddDaemon] = "+ 新增 daemon",
            [DesktopTextKey.DeployDaemon] = "部署 daemon",
            [DesktopTextKey.RetireDaemon] = "退役 daemon",
            [DesktopTextKey.ProvisionGewyvern] = "部署 gewyvern",
            [DesktopTextKey.RetireGewyvern] = "退役 gewyvern",
            [DesktopTextKey.ControlTopology] = "控制拓撲",
            [DesktopTextKey.HubSubcopy] = "一個客戶端可管理多個 daemon 權威端；開啟 daemon 即可管理其下屬的 gewyvern runtime。",
            [DesktopTextKey.FindDaemonOrRuntime] = "查找 daemon 或 runtime",
            [DesktopTextKey.NoTopologyMatches] = "沒有符合目前篩選條件的 daemon 權威端或 runtime。",
            [DesktopTextKey.NoAuthorities] = "尚未設定 daemon 權威端。新增一個即可建立第一條拓撲分支。",
            [DesktopTextKey.LocalOrchestra] = "本機 Orchestra",
            [DesktopTextKey.ManagedOnDevice] = "由此裝置管理",
            [DesktopTextKey.Local] = "本機",
            [DesktopTextKey.EphemeralSessionAuthority] = "暫時性工作階段權威端",
            [DesktopTextKey.LanguageSettingsTitle] = "Leserpent / 語言",
            [DesktopTextKey.LanguageSettingsKicker] = "介面語言",
            [DesktopTextKey.LanguageSettingsHeading] = "選擇 Leserpent 的介面語言",
            [DesktopTextKey.LanguageSettingsBody] = "此偏好會套用至原生 shell、學習中心、輔助使用名稱和已本地化的 UI-IR 文字。缺少的詞條會確定性回退英文，動作識別碼不會改變。",
            [DesktopTextKey.LanguagePreference] = "語言偏好",
            [DesktopTextKey.DesktopCoverage] = "桌面端覆蓋範圍",
            [DesktopTextKey.CoverageComplete] = "完整桌面 shell 與學習中心",
            [DesktopTextKey.CoverageCore] = "核心桌面 shell；延伸畫面回退英文",
            [DesktopTextKey.CoverageFallback] = "官方語言已可選；桌面專用文字目前回退英文",
            [DesktopTextKey.AppliesImmediately] = "立即生效，且只儲存在此裝置上。",
            [DesktopTextKey.TutorialKicker] = "LESERPENT 學習中心",
            [DesktopTextKey.TutorialHeading] = "六步操作員導覽",
            [DesktopTextKey.TutorialBody] = "離線、唯讀，並可隨時重新查看。此視窗不會發起連線、部署或命令。",
            [DesktopTextKey.Previous] = "上一步",
            [DesktopTextKey.Next] = "下一步",
            [DesktopTextKey.Finish] = "完成",
            [DesktopTextKey.StepProgress] = "第 {0} 步，共 {1} 步",
            [DesktopTextKey.AboutDescription] = "面向 Gewyvern 的原生編排與模型驅動控制。",
            [DesktopTextKey.Version] = "版本 {0}",
            [DesktopTextKey.Dismiss] = "收起",
            [DesktopTextKey.Reconnect] = "重新連線",
            [DesktopTextKey.FilterRuntimes] = "依名稱、ID、標籤或狀態篩選 runtime",
            [DesktopTextKey.AwaitingAuthorityCheck] = "權威端 / 等待檢查",
            [DesktopTextKey.RefreshHealth] = "刷新健康狀態",
            [DesktopTextKey.RemoteConnectionState] = "遠端連線狀態",
            [DesktopTextKey.RemoteOperationStatus] = "遠端操作狀態",
            [DesktopTextKey.ManageConnection] = "管理遠端連線",
            [DesktopTextKey.RuntimeResultCount] = "遠端 runtime 結果數量",
            [DesktopTextKey.Reload] = "重新載入",
            [DesktopTextKey.LiveLogs] = "即時日誌",
            [DesktopTextKey.Acknowledge] = "確認告警",
            [DesktopTextKey.SearchSanitizedLogs] = "搜尋淨化後的日誌",
            [DesktopTextKey.CopyDiagnostics] = "複製診斷資訊",
            [DesktopTextKey.SaveDiagnostics] = "儲存診斷資訊",
            [DesktopTextKey.WorkspaceLeselang] = "工作區 Leselang",
            [DesktopTextKey.LogsLoadWithSnapshot] = "日誌會隨 runtime 快照載入",
            [DesktopTextKey.RequiredSuffix] = "{0}（必填）",
        });

    public static IReadOnlyDictionary<DesktopTextKey, string> Japanese { get; } =
        Catalog(new Dictionary<DesktopTextKey, string>
        {
            [DesktopTextKey.AboutLeserpent] = "Leserpent について",
            [DesktopTextKey.LearningCenter] = "ラーニングセンター...",
            [DesktopTextKey.Connection] = "接続...",
            [DesktopTextKey.Language] = "言語...",
            [DesktopTextKey.ShowLeserpent] = "Leserpent を表示",
            [DesktopTextKey.QuitLeserpent] = "Leserpent を終了",
            [DesktopTextKey.Close] = "閉じる",
            [DesktopTextKey.Cancel] = "キャンセル",
            [DesktopTextKey.Apply] = "適用",
            [DesktopTextKey.Clear] = "クリア",
            [DesktopTextKey.Open] = "開く",
            [DesktopTextKey.Refresh] = "更新",
            [DesktopTextKey.Manage] = "管理",
            [DesktopTextKey.RefreshAll] = "すべて更新",
            [DesktopTextKey.FollowSystem] = "システムに従う",
            [DesktopTextKey.QuickTour] = "クイックツアー",
            [DesktopTextKey.AddDaemon] = "+ daemon を追加",
            [DesktopTextKey.DeployDaemon] = "daemon をデプロイ",
            [DesktopTextKey.RetireDaemon] = "daemon を廃止",
            [DesktopTextKey.ProvisionGewyvern] = "gewyvern をプロビジョニング",
            [DesktopTextKey.RetireGewyvern] = "gewyvern を廃止",
            [DesktopTextKey.ControlTopology] = "トポロジーを管理",
            [DesktopTextKey.HubSubcopy] = "1 つのクライアントで複数の daemon 権威を管理します。daemon を開くと、その配下の gewyvern runtime を管理できます。",
            [DesktopTextKey.FindDaemonOrRuntime] = "daemon または runtime を検索",
            [DesktopTextKey.NoTopologyMatches] = "現在のフィルターに一致する daemon 権威または runtime はありません。",
            [DesktopTextKey.NoAuthorities] = "daemon 権威が設定されていません。追加すると最初のトポロジーブランチが作成されます。",
            [DesktopTextKey.LocalOrchestra] = "ローカル Orchestra",
            [DesktopTextKey.ManagedOnDevice] = "このデバイスで管理",
            [DesktopTextKey.Local] = "ローカル",
            [DesktopTextKey.EphemeralSessionAuthority] = "一時セッション権威",
            [DesktopTextKey.LanguageSettingsTitle] = "Leserpent / 言語",
            [DesktopTextKey.LanguageSettingsKicker] = "表示言語",
            [DesktopTextKey.LanguageSettingsHeading] = "Leserpent の表示言語を選択",
            [DesktopTextKey.LanguageSettingsBody] = "この設定はネイティブ shell、ラーニングセンター、アクセシビリティ名、ローカライズ済み UI-IR テキストに適用されます。未翻訳のキーはアクション ID を変えずに英語へフォールバックします。",
            [DesktopTextKey.LanguagePreference] = "言語設定",
            [DesktopTextKey.DesktopCoverage] = "デスクトップ対応範囲",
            [DesktopTextKey.CoverageComplete] = "デスクトップ shell とラーニングセンターを完全対応",
            [DesktopTextKey.CoverageCore] = "主要デスクトップ shell に対応。拡張画面は英語へフォールバック",
            [DesktopTextKey.CoverageFallback] = "公式ロケールを選択可能。デスクトップ固有テキストは現在英語へフォールバック",
            [DesktopTextKey.AppliesImmediately] = "すぐに適用され、このデバイスだけに保存されます。",
            [DesktopTextKey.TutorialKicker] = "LESERPENT ラーニングセンター",
            [DesktopTextKey.TutorialHeading] = "6 ステップのオペレーターツアー",
            [DesktopTextKey.TutorialBody] = "オフラインかつ読み取り専用で、いつでも見直せます。このウィンドウから接続、デプロイ、コマンドは開始されません。",
            [DesktopTextKey.Previous] = "前へ",
            [DesktopTextKey.Next] = "次へ",
            [DesktopTextKey.Finish] = "完了",
            [DesktopTextKey.StepProgress] = "{1} ステップ中 {0}",
            [DesktopTextKey.AboutDescription] = "Gewyvern 向けのネイティブオーケストレーションとモデル駆動制御。",
            [DesktopTextKey.Version] = "バージョン {0}",
            [DesktopTextKey.Dismiss] = "閉じる",
            [DesktopTextKey.Reconnect] = "再接続",
            [DesktopTextKey.FilterRuntimes] = "名前、ID、タグ、状態で runtime を絞り込み",
            [DesktopTextKey.AwaitingAuthorityCheck] = "権威 / 確認待ち",
            [DesktopTextKey.RefreshHealth] = "ヘルス状態を更新",
            [DesktopTextKey.RemoteConnectionState] = "リモート接続状態",
            [DesktopTextKey.RemoteOperationStatus] = "リモート操作状態",
            [DesktopTextKey.ManageConnection] = "リモート接続を管理",
            [DesktopTextKey.RuntimeResultCount] = "リモート runtime の件数",
            [DesktopTextKey.Reload] = "再読み込み",
            [DesktopTextKey.LiveLogs] = "ライブログ",
            [DesktopTextKey.Acknowledge] = "アラートを確認",
            [DesktopTextKey.SearchSanitizedLogs] = "サニタイズ済みログを検索",
            [DesktopTextKey.CopyDiagnostics] = "診断情報をコピー",
            [DesktopTextKey.SaveDiagnostics] = "診断情報を保存",
            [DesktopTextKey.WorkspaceLeselang] = "ワークスペース Leselang",
            [DesktopTextKey.LogsLoadWithSnapshot] = "ログは runtime スナップショットと共に読み込まれます",
            [DesktopTextKey.RequiredSuffix] = "{0}（必須）",
        });

    public static IReadOnlyDictionary<DesktopTextKey, string> Spanish { get; } =
        Catalog(new Dictionary<DesktopTextKey, string>
        {
            [DesktopTextKey.AboutLeserpent] = "Acerca de Leserpent",
            [DesktopTextKey.LearningCenter] = "Centro de aprendizaje...",
            [DesktopTextKey.Connection] = "Conexión...",
            [DesktopTextKey.Language] = "Idioma...",
            [DesktopTextKey.ShowLeserpent] = "Mostrar Leserpent",
            [DesktopTextKey.QuitLeserpent] = "Salir de Leserpent",
            [DesktopTextKey.Close] = "Cerrar",
            [DesktopTextKey.Cancel] = "Cancelar",
            [DesktopTextKey.Apply] = "Aplicar",
            [DesktopTextKey.Clear] = "Limpiar",
            [DesktopTextKey.Open] = "Abrir",
            [DesktopTextKey.Refresh] = "Actualizar",
            [DesktopTextKey.Manage] = "Administrar",
            [DesktopTextKey.RefreshAll] = "Actualizar todo",
            [DesktopTextKey.FollowSystem] = "Seguir el sistema",
            [DesktopTextKey.QuickTour] = "Recorrido rápido",
            [DesktopTextKey.AddDaemon] = "+ Añadir daemon",
            [DesktopTextKey.DeployDaemon] = "Desplegar daemon",
            [DesktopTextKey.RetireDaemon] = "Retirar daemon",
            [DesktopTextKey.ProvisionGewyvern] = "Aprovisionar gewyvern",
            [DesktopTextKey.RetireGewyvern] = "Retirar gewyvern",
            [DesktopTextKey.ControlTopology] = "Controlar la topología",
            [DesktopTextKey.HubSubcopy] = "Un cliente administra varias autoridades daemon. Abre un daemon para administrar sus runtimes gewyvern.",
            [DesktopTextKey.FindDaemonOrRuntime] = "Buscar un daemon o runtime",
            [DesktopTextKey.NoTopologyMatches] = "Ninguna autoridad daemon ni runtime coincide con este filtro.",
            [DesktopTextKey.NoAuthorities] = "No hay autoridades daemon configuradas. Añade una para crear la primera rama de la topología.",
            [DesktopTextKey.LocalOrchestra] = "Orchestra local",
            [DesktopTextKey.ManagedOnDevice] = "Administrado en este dispositivo",
            [DesktopTextKey.Local] = "LOCAL",
            [DesktopTextKey.EphemeralSessionAuthority] = "Autoridad de sesión efímera",
            [DesktopTextKey.LanguageSettingsTitle] = "Leserpent / Idioma",
            [DesktopTextKey.LanguageSettingsKicker] = "IDIOMA DE LA INTERFAZ",
            [DesktopTextKey.LanguageSettingsHeading] = "Elige el idioma de Leserpent",
            [DesktopTextKey.LanguageSettingsBody] = "La preferencia se aplica al shell nativo, el Centro de aprendizaje, los nombres accesibles y el texto UI-IR localizado. Las claves ausentes vuelven al inglés sin cambiar las identidades de las acciones.",
            [DesktopTextKey.LanguagePreference] = "Preferencia de idioma",
            [DesktopTextKey.DesktopCoverage] = "Cobertura de escritorio",
            [DesktopTextKey.CoverageComplete] = "Shell de escritorio y Centro de aprendizaje completos",
            [DesktopTextKey.CoverageCore] = "Shell de escritorio principal; las vistas ampliadas vuelven al inglés",
            [DesktopTextKey.CoverageFallback] = "Idioma oficial disponible; el texto específico de escritorio usa actualmente el inglés",
            [DesktopTextKey.AppliesImmediately] = "Se aplica de inmediato y solo se guarda en este dispositivo.",
            [DesktopTextKey.TutorialKicker] = "CENTRO DE APRENDIZAJE DE LESERPENT",
            [DesktopTextKey.TutorialHeading] = "Recorrido del operador en seis pasos",
            [DesktopTextKey.TutorialBody] = "Sin conexión, de solo lectura y disponible para volver a consultarlo. Esta ventana no inicia conexiones, despliegues ni comandos.",
            [DesktopTextKey.Previous] = "Anterior",
            [DesktopTextKey.Next] = "Siguiente",
            [DesktopTextKey.Finish] = "Finalizar",
            [DesktopTextKey.StepProgress] = "Paso {0} de {1}",
            [DesktopTextKey.AboutDescription] = "Orquestación nativa y control basado en modelos para Gewyvern.",
            [DesktopTextKey.Version] = "Versión {0}",
            [DesktopTextKey.Dismiss] = "Ocultar",
            [DesktopTextKey.Reconnect] = "Reconectar",
            [DesktopTextKey.FilterRuntimes] = "Filtrar runtimes por nombre, ID, etiqueta o estado",
            [DesktopTextKey.AwaitingAuthorityCheck] = "AUTORIDAD / esperando comprobación",
            [DesktopTextKey.RefreshHealth] = "Actualizar estado",
            [DesktopTextKey.RemoteConnectionState] = "Estado de la conexión remota",
            [DesktopTextKey.RemoteOperationStatus] = "Estado de la operación remota",
            [DesktopTextKey.ManageConnection] = "Administrar la conexión remota",
            [DesktopTextKey.RuntimeResultCount] = "Número de runtimes remotos",
            [DesktopTextKey.Reload] = "Recargar",
            [DesktopTextKey.LiveLogs] = "Registros en vivo",
            [DesktopTextKey.Acknowledge] = "Confirmar alerta",
            [DesktopTextKey.SearchSanitizedLogs] = "Buscar registros saneados",
            [DesktopTextKey.CopyDiagnostics] = "Copiar diagnóstico",
            [DesktopTextKey.SaveDiagnostics] = "Guardar diagnóstico",
            [DesktopTextKey.WorkspaceLeselang] = "Leselang del espacio de trabajo",
            [DesktopTextKey.LogsLoadWithSnapshot] = "Los registros se cargan con la instantánea del runtime",
            [DesktopTextKey.RequiredSuffix] = "{0} (obligatorio)",
        });

    public static IReadOnlyDictionary<DesktopTextKey, string> German { get; } =
        Catalog(new Dictionary<DesktopTextKey, string>
        {
            [DesktopTextKey.AboutLeserpent] = "Über Leserpent",
            [DesktopTextKey.LearningCenter] = "Lernzentrum...",
            [DesktopTextKey.Connection] = "Verbindung...",
            [DesktopTextKey.Language] = "Sprache...",
            [DesktopTextKey.ShowLeserpent] = "Leserpent anzeigen",
            [DesktopTextKey.QuitLeserpent] = "Leserpent beenden",
            [DesktopTextKey.Close] = "Schließen",
            [DesktopTextKey.Cancel] = "Abbrechen",
            [DesktopTextKey.Apply] = "Anwenden",
            [DesktopTextKey.Clear] = "Zurücksetzen",
            [DesktopTextKey.Open] = "Öffnen",
            [DesktopTextKey.Refresh] = "Aktualisieren",
            [DesktopTextKey.Manage] = "Verwalten",
            [DesktopTextKey.RefreshAll] = "Alle aktualisieren",
            [DesktopTextKey.FollowSystem] = "System folgen",
            [DesktopTextKey.QuickTour] = "Kurztour",
            [DesktopTextKey.AddDaemon] = "+ Daemon hinzufügen",
            [DesktopTextKey.DeployDaemon] = "Daemon bereitstellen",
            [DesktopTextKey.RetireDaemon] = "Daemon außer Betrieb nehmen",
            [DesktopTextKey.ProvisionGewyvern] = "gewyvern bereitstellen",
            [DesktopTextKey.RetireGewyvern] = "gewyvern außer Betrieb nehmen",
            [DesktopTextKey.ControlTopology] = "Topologie steuern",
            [DesktopTextKey.HubSubcopy] = "Ein Client verwaltet mehrere Daemon-Autoritäten. Öffnen Sie einen Daemon, um dessen gewyvern-Runtimes zu verwalten.",
            [DesktopTextKey.FindDaemonOrRuntime] = "Daemon oder Runtime suchen",
            [DesktopTextKey.NoTopologyMatches] = "Keine Daemon-Autorität oder Runtime entspricht diesem Filter.",
            [DesktopTextKey.NoAuthorities] = "Es sind keine Daemon-Autoritäten konfiguriert. Fügen Sie eine hinzu, um den ersten Topologiezweig anzulegen.",
            [DesktopTextKey.LocalOrchestra] = "Lokale Orchestra",
            [DesktopTextKey.ManagedOnDevice] = "Auf diesem Gerät verwaltet",
            [DesktopTextKey.Local] = "LOKAL",
            [DesktopTextKey.EphemeralSessionAuthority] = "Temporäre Sitzungsautorität",
            [DesktopTextKey.LanguageSettingsTitle] = "Leserpent / Sprache",
            [DesktopTextKey.LanguageSettingsKicker] = "OBERFLÄCHENSPRACHE",
            [DesktopTextKey.LanguageSettingsHeading] = "Anzeigesprache für Leserpent wählen",
            [DesktopTextKey.LanguageSettingsBody] = "Die Einstellung gilt für die native Shell, das Lernzentrum, barrierefreie Namen und lokalisierte UI-IR-Texte. Fehlende Schlüssel fallen auf Englisch zurück, ohne Aktionsidentitäten zu verändern.",
            [DesktopTextKey.LanguagePreference] = "Spracheinstellung",
            [DesktopTextKey.DesktopCoverage] = "Desktop-Abdeckung",
            [DesktopTextKey.CoverageComplete] = "Vollständige Desktop-Shell und vollständiges Lernzentrum",
            [DesktopTextKey.CoverageCore] = "Zentrale Desktop-Shell; erweiterte Ansichten fallen auf Englisch zurück",
            [DesktopTextKey.CoverageFallback] = "Offizielle Sprache verfügbar; Desktop-spezifische Texte verwenden derzeit Englisch",
            [DesktopTextKey.AppliesImmediately] = "Wird sofort angewendet und nur auf diesem Gerät gespeichert.",
            [DesktopTextKey.TutorialKicker] = "LESERPENT LERNZENTRUM",
            [DesktopTextKey.TutorialHeading] = "Operator-Tour in sechs Schritten",
            [DesktopTextKey.TutorialBody] = "Offline, schreibgeschützt und jederzeit erneut aufrufbar. Dieses Fenster startet keine Verbindung, Bereitstellung oder Befehle.",
            [DesktopTextKey.Previous] = "Zurück",
            [DesktopTextKey.Next] = "Weiter",
            [DesktopTextKey.Finish] = "Abschließen",
            [DesktopTextKey.StepProgress] = "Schritt {0} von {1}",
            [DesktopTextKey.AboutDescription] = "Native Orchestrierung und modellgesteuerte Steuerung für Gewyvern.",
            [DesktopTextKey.Version] = "Version {0}",
            [DesktopTextKey.Dismiss] = "Ausblenden",
            [DesktopTextKey.Reconnect] = "Neu verbinden",
            [DesktopTextKey.FilterRuntimes] = "Runtimes nach Name, ID, Tag oder Status filtern",
            [DesktopTextKey.AwaitingAuthorityCheck] = "AUTORITÄT / Prüfung ausstehend",
            [DesktopTextKey.RefreshHealth] = "Zustand aktualisieren",
            [DesktopTextKey.RemoteConnectionState] = "Status der Remote-Verbindung",
            [DesktopTextKey.RemoteOperationStatus] = "Status des Remote-Vorgangs",
            [DesktopTextKey.ManageConnection] = "Remote-Verbindung verwalten",
            [DesktopTextKey.RuntimeResultCount] = "Anzahl der Remote-Runtimes",
            [DesktopTextKey.Reload] = "Neu laden",
            [DesktopTextKey.LiveLogs] = "Live-Protokolle",
            [DesktopTextKey.Acknowledge] = "Warnung bestätigen",
            [DesktopTextKey.SearchSanitizedLogs] = "Bereinigte Protokolle durchsuchen",
            [DesktopTextKey.CopyDiagnostics] = "Diagnose kopieren",
            [DesktopTextKey.SaveDiagnostics] = "Diagnose speichern",
            [DesktopTextKey.WorkspaceLeselang] = "Arbeitsbereich-Leselang",
            [DesktopTextKey.LogsLoadWithSnapshot] = "Protokolle werden mit dem Runtime-Snapshot geladen",
            [DesktopTextKey.RequiredSuffix] = "{0} (erforderlich)",
        });

    public static IReadOnlyDictionary<DesktopTextKey, string> French { get; } =
        Catalog(new Dictionary<DesktopTextKey, string>
        {
            [DesktopTextKey.AboutLeserpent] = "À propos de Leserpent",
            [DesktopTextKey.LearningCenter] = "Centre d’apprentissage...",
            [DesktopTextKey.Connection] = "Connexion...",
            [DesktopTextKey.Language] = "Langue...",
            [DesktopTextKey.ShowLeserpent] = "Afficher Leserpent",
            [DesktopTextKey.QuitLeserpent] = "Quitter Leserpent",
            [DesktopTextKey.Close] = "Fermer",
            [DesktopTextKey.Cancel] = "Annuler",
            [DesktopTextKey.Apply] = "Appliquer",
            [DesktopTextKey.Clear] = "Effacer",
            [DesktopTextKey.Open] = "Ouvrir",
            [DesktopTextKey.Refresh] = "Rafraîchir",
            [DesktopTextKey.Manage] = "Gérer",
            [DesktopTextKey.RefreshAll] = "Tout rafraîchir",
            [DesktopTextKey.FollowSystem] = "Suivre le système",
            [DesktopTextKey.QuickTour] = "Visite rapide",
            [DesktopTextKey.AddDaemon] = "+ Ajouter un daemon",
            [DesktopTextKey.DeployDaemon] = "Déployer un daemon",
            [DesktopTextKey.RetireDaemon] = "Retirer un daemon",
            [DesktopTextKey.ProvisionGewyvern] = "Provisionner gewyvern",
            [DesktopTextKey.RetireGewyvern] = "Retirer gewyvern",
            [DesktopTextKey.ControlTopology] = "Piloter la topologie",
            [DesktopTextKey.HubSubcopy] = "Un client gère plusieurs autorités daemon. Ouvrez un daemon pour gérer ses runtimes gewyvern.",
            [DesktopTextKey.FindDaemonOrRuntime] = "Rechercher un daemon ou un runtime",
            [DesktopTextKey.NoTopologyMatches] = "Aucune autorité daemon ni aucun runtime ne correspond à ce filtre.",
            [DesktopTextKey.NoAuthorities] = "Aucune autorité daemon n’est configurée. Ajoutez-en une pour créer la première branche de topologie.",
            [DesktopTextKey.LocalOrchestra] = "Orchestra locale",
            [DesktopTextKey.ManagedOnDevice] = "Gérée sur cet appareil",
            [DesktopTextKey.Local] = "LOCAL",
            [DesktopTextKey.EphemeralSessionAuthority] = "Autorité de session éphémère",
            [DesktopTextKey.LanguageSettingsTitle] = "Leserpent / Langue",
            [DesktopTextKey.LanguageSettingsKicker] = "LANGUE DE L’INTERFACE",
            [DesktopTextKey.LanguageSettingsHeading] = "Choisissez la langue de Leserpent",
            [DesktopTextKey.LanguageSettingsBody] = "La préférence s’applique au shell natif, au Centre d’apprentissage, aux noms accessibles et au texte UI-IR localisé. Les clés absentes reviennent à l’anglais sans modifier l’identité des actions.",
            [DesktopTextKey.LanguagePreference] = "Préférence linguistique",
            [DesktopTextKey.DesktopCoverage] = "Couverture du bureau",
            [DesktopTextKey.CoverageComplete] = "Shell de bureau et Centre d’apprentissage complets",
            [DesktopTextKey.CoverageCore] = "Shell de bureau principal ; les vues étendues reviennent à l’anglais",
            [DesktopTextKey.CoverageFallback] = "Langue officielle disponible ; le texte propre au bureau utilise actuellement l’anglais",
            [DesktopTextKey.AppliesImmediately] = "S’applique immédiatement et n’est enregistré que sur cet appareil.",
            [DesktopTextKey.TutorialKicker] = "CENTRE D’APPRENTISSAGE LESERPENT",
            [DesktopTextKey.TutorialHeading] = "Visite opérateur en six étapes",
            [DesktopTextKey.TutorialBody] = "Hors ligne, en lecture seule et disponible à tout moment. Cette fenêtre ne lance aucune connexion, aucun déploiement ni aucune commande.",
            [DesktopTextKey.Previous] = "Précédent",
            [DesktopTextKey.Next] = "Suivant",
            [DesktopTextKey.Finish] = "Terminer",
            [DesktopTextKey.StepProgress] = "Étape {0} sur {1}",
            [DesktopTextKey.AboutDescription] = "Orchestration native et contrôle piloté par modèle pour Gewyvern.",
            [DesktopTextKey.Version] = "Version {0}",
            [DesktopTextKey.Dismiss] = "Masquer",
            [DesktopTextKey.Reconnect] = "Reconnecter",
            [DesktopTextKey.FilterRuntimes] = "Filtrer les runtimes par nom, ID, étiquette ou état",
            [DesktopTextKey.AwaitingAuthorityCheck] = "AUTORITÉ / vérification en attente",
            [DesktopTextKey.RefreshHealth] = "Rafraîchir l’état de santé",
            [DesktopTextKey.RemoteConnectionState] = "État de la connexion distante",
            [DesktopTextKey.RemoteOperationStatus] = "État de l’opération distante",
            [DesktopTextKey.ManageConnection] = "Gérer la connexion distante",
            [DesktopTextKey.RuntimeResultCount] = "Nombre de runtimes distants",
            [DesktopTextKey.Reload] = "Recharger",
            [DesktopTextKey.LiveLogs] = "Journaux en direct",
            [DesktopTextKey.Acknowledge] = "Acquitter l’alerte",
            [DesktopTextKey.SearchSanitizedLogs] = "Rechercher dans les journaux nettoyés",
            [DesktopTextKey.CopyDiagnostics] = "Copier le diagnostic",
            [DesktopTextKey.SaveDiagnostics] = "Enregistrer le diagnostic",
            [DesktopTextKey.WorkspaceLeselang] = "Leselang de l’espace de travail",
            [DesktopTextKey.LogsLoadWithSnapshot] = "Les journaux sont chargés avec l’instantané du runtime",
            [DesktopTextKey.RequiredSuffix] = "{0} (obligatoire)",
        });

    public static IReadOnlyDictionary<DesktopTextKey, string> Korean { get; } =
        Catalog(new Dictionary<DesktopTextKey, string>
        {
            [DesktopTextKey.AboutLeserpent] = "Leserpent 정보",
            [DesktopTextKey.LearningCenter] = "학습 센터...",
            [DesktopTextKey.Connection] = "연결...",
            [DesktopTextKey.Language] = "언어...",
            [DesktopTextKey.ShowLeserpent] = "Leserpent 표시",
            [DesktopTextKey.QuitLeserpent] = "Leserpent 종료",
            [DesktopTextKey.Close] = "닫기",
            [DesktopTextKey.Cancel] = "취소",
            [DesktopTextKey.Apply] = "적용",
            [DesktopTextKey.Clear] = "지우기",
            [DesktopTextKey.Open] = "열기",
            [DesktopTextKey.Refresh] = "새로고침",
            [DesktopTextKey.Manage] = "관리",
            [DesktopTextKey.RefreshAll] = "모두 새로고침",
            [DesktopTextKey.FollowSystem] = "시스템 따르기",
            [DesktopTextKey.QuickTour] = "빠른 둘러보기",
            [DesktopTextKey.AddDaemon] = "+ daemon 추가",
            [DesktopTextKey.DeployDaemon] = "daemon 배포",
            [DesktopTextKey.RetireDaemon] = "daemon 사용 중지",
            [DesktopTextKey.ProvisionGewyvern] = "gewyvern 프로비저닝",
            [DesktopTextKey.RetireGewyvern] = "gewyvern 사용 중지",
            [DesktopTextKey.ControlTopology] = "토폴로지 제어",
            [DesktopTextKey.HubSubcopy] = "하나의 클라이언트에서 여러 daemon 권한 주체를 관리합니다. daemon을 열어 하위 gewyvern runtime을 관리하세요.",
            [DesktopTextKey.FindDaemonOrRuntime] = "daemon 또는 runtime 찾기",
            [DesktopTextKey.NoTopologyMatches] = "이 필터와 일치하는 daemon 권한 주체 또는 runtime이 없습니다.",
            [DesktopTextKey.NoAuthorities] = "구성된 daemon 권한 주체가 없습니다. 첫 번째 토폴로지 분기를 만들려면 하나를 추가하세요.",
            [DesktopTextKey.LocalOrchestra] = "로컬 Orchestra",
            [DesktopTextKey.ManagedOnDevice] = "이 기기에서 관리",
            [DesktopTextKey.Local] = "로컬",
            [DesktopTextKey.EphemeralSessionAuthority] = "임시 세션 권한 주체",
            [DesktopTextKey.LanguageSettingsTitle] = "Leserpent / 언어",
            [DesktopTextKey.LanguageSettingsKicker] = "인터페이스 언어",
            [DesktopTextKey.LanguageSettingsHeading] = "Leserpent에서 사용할 언어 선택",
            [DesktopTextKey.LanguageSettingsBody] = "이 설정은 네이티브 shell, 학습 센터, 접근성 이름, 현지화된 UI-IR 텍스트에 적용됩니다. 누락된 키는 작업 ID를 변경하지 않고 영어로 대체됩니다.",
            [DesktopTextKey.LanguagePreference] = "언어 설정",
            [DesktopTextKey.DesktopCoverage] = "데스크톱 적용 범위",
            [DesktopTextKey.CoverageComplete] = "완전한 데스크톱 shell 및 학습 센터",
            [DesktopTextKey.CoverageCore] = "핵심 데스크톱 shell 지원. 확장 화면은 영어로 대체",
            [DesktopTextKey.CoverageFallback] = "공식 언어 선택 가능. 데스크톱 전용 텍스트는 현재 영어로 대체",
            [DesktopTextKey.AppliesImmediately] = "즉시 적용되며 이 기기에만 저장됩니다.",
            [DesktopTextKey.TutorialKicker] = "LESERPENT 학습 센터",
            [DesktopTextKey.TutorialHeading] = "6단계 운영자 둘러보기",
            [DesktopTextKey.TutorialBody] = "오프라인 읽기 전용이며 언제든 다시 볼 수 있습니다. 이 창에서는 연결, 배포 또는 명령이 시작되지 않습니다.",
            [DesktopTextKey.Previous] = "이전",
            [DesktopTextKey.Next] = "다음",
            [DesktopTextKey.Finish] = "완료",
            [DesktopTextKey.StepProgress] = "{1}단계 중 {0}단계",
            [DesktopTextKey.AboutDescription] = "Gewyvern을 위한 네이티브 오케스트레이션과 모델 기반 제어.",
            [DesktopTextKey.Version] = "버전 {0}",
            [DesktopTextKey.Dismiss] = "숨기기",
            [DesktopTextKey.Reconnect] = "다시 연결",
            [DesktopTextKey.FilterRuntimes] = "이름, ID, 태그 또는 상태로 runtime 필터링",
            [DesktopTextKey.AwaitingAuthorityCheck] = "권한 주체 / 확인 대기 중",
            [DesktopTextKey.RefreshHealth] = "상태 새로고침",
            [DesktopTextKey.RemoteConnectionState] = "원격 연결 상태",
            [DesktopTextKey.RemoteOperationStatus] = "원격 작업 상태",
            [DesktopTextKey.ManageConnection] = "원격 연결 관리",
            [DesktopTextKey.RuntimeResultCount] = "원격 runtime 결과 수",
            [DesktopTextKey.Reload] = "다시 로드",
            [DesktopTextKey.LiveLogs] = "실시간 로그",
            [DesktopTextKey.Acknowledge] = "알림 확인",
            [DesktopTextKey.SearchSanitizedLogs] = "정제된 로그 검색",
            [DesktopTextKey.CopyDiagnostics] = "진단 복사",
            [DesktopTextKey.SaveDiagnostics] = "진단 저장",
            [DesktopTextKey.WorkspaceLeselang] = "작업 영역 Leselang",
            [DesktopTextKey.LogsLoadWithSnapshot] = "로그는 runtime 스냅샷과 함께 로드됩니다",
            [DesktopTextKey.RequiredSuffix] = "{0}(필수)",
        });

    public static void VerifyContract()
    {
        var expected = Enum.GetValues<DesktopTextKey>().Length;
        foreach (var catalog in All)
        {
            if (catalog.Count != expected
                || catalog.Any(entry => entry.Value.Length is <= 0 or > 1024
                    || entry.Value.Any(char.IsControl)))
            {
                throw new InvalidDataException("built-in desktop shell catalog is incomplete");
            }
            VerifyFormat(catalog[DesktopTextKey.StepProgress], 1, 6);
            VerifyFormat(catalog[DesktopTextKey.Version], "1.15.0");
            VerifyFormat(catalog[DesktopTextKey.RequiredSuffix], "Target");
        }
    }

    private static IReadOnlyList<IReadOnlyDictionary<DesktopTextKey, string>> All =>
        [TraditionalChinese, Japanese, Spanish, German, French, Korean];

    private static IReadOnlyDictionary<DesktopTextKey, string> Catalog(
        Dictionary<DesktopTextKey, string> values) => values;

    private static void VerifyFormat(string format, params object[] values)
    {
        try
        {
            var result = string.Format(
                System.Globalization.CultureInfo.InvariantCulture,
                format,
                values);
            if (string.IsNullOrWhiteSpace(result) || result.Any(char.IsControl))
            {
                throw new InvalidDataException("built-in desktop format produced invalid text");
            }
        }
        catch (FormatException error)
        {
            throw new InvalidDataException("built-in desktop format is invalid", error);
        }
    }
}
