using System.Globalization;

internal static class DesktopDaemonRetirementCatalogs
{
    private const string Prefix = "desktop.daemon_retirement.";
    public const int KeyCount = 37;

    public static IReadOnlyDictionary<string, string> English { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["title"] = "Leserpent / Retire daemon",
            ["confirmation"] = "I confirm removal of the leserpentd service created by this bootstrap",
            ["submit"] = "Retire daemon",
            ["refresh"] = "Refresh same attempt",
            ["close"] = "Close",
            ["status.initial"] = "Choose the daemon authority that performed the original bootstrap.",
            ["status.name"] = "Daemon retirement status",
            ["phase.name"] = "Daemon retirement phase",
            ["kicker"] = "DAEMON RETIREMENT",
            ["heading"] = "Remove a bootstrapped authority",
            ["body"] = "The controller derives host, daemon, generation, and install profile from the bound bootstrap checkpoint. This form cannot override that authority.",
            ["authority.label"] = "Controlling daemon authority",
            ["retirement_id.label"] = "Retirement ID",
            ["bootstrap_id.label"] = "Original bootstrap ID",
            ["credential.label"] = "SSH credential handle",
            ["a11y.authority"] = "Daemon authority owning the original bootstrap",
            ["a11y.retirement_id"] = "Stable daemon retirement operation ID",
            ["a11y.bootstrap_id"] = "Original bootstrap authority ID",
            ["a11y.credential"] = "Opaque SSH credential handle",
            ["a11y.confirm"] = "Confirm leserpent daemon removal",
            ["a11y.submit"] = "Retire the bootstrapped daemon service",
            ["a11y.refresh"] = "Refresh the same daemon retirement attempt",
            ["a11y.close"] = "Close daemon retirement window",
            ["phase.not_submitted"] = "NOT SUBMITTED",
            ["phase.planned"] = "PLANNED",
            ["phase.retiring_service"] = "RETIRING SERVICE",
            ["phase.service_retired"] = "SERVICE RETIRED",
            ["phase.failed"] = "FAILED",
            ["error.confirm_required"] = "Confirm daemon retirement before submitting.",
            ["error.authority_required"] = "Select the controlling daemon authority first.",
            ["status.observation_limit"] = "Automatic observation reached its bounded limit. Use Refresh same attempt to inspect this exact retirement ID without creating another removal.",
            ["status.waiting"] = "Waiting for the selected daemon authority...",
            ["status.planned"] = "Retirement is durably queued for bootstrap {0}. Derived target authority is locked to daemon {1}.",
            ["status.retiring_service"] = "The controller is removing daemon {0} on its checkpoint-derived {1} profile.",
            ["status.service_retired"] = "Daemon {0} was retired from {1}:{2}. Remove any now-offline Hub connection separately.",
            ["status.failed"] = "Daemon retirement failed with bounded fault {0}. The service was not marked retired; inspect the controller and use a new retirement ID after remediation.",
            ["unavailable"] = "unavailable",
        });

    public static IReadOnlyDictionary<string, string> SimplifiedChinese { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["title"] = "Leserpent / 退役 daemon",
            ["confirmation"] = "我确认移除此 bootstrap 创建的 leserpentd 服务",
            ["submit"] = "退役 daemon",
            ["refresh"] = "刷新同一尝试",
            ["close"] = "关闭",
            ["status.initial"] = "请选择执行原始 bootstrap 的 daemon 权威端。",
            ["status.name"] = "Daemon 退役状态",
            ["phase.name"] = "Daemon 退役阶段",
            ["kicker"] = "DAEMON 退役",
            ["heading"] = "移除已 bootstrap 的权威端",
            ["body"] = "控制器会从绑定的 bootstrap 检查点推导主机、daemon、代次和安装配置。此表单无法覆盖该权威信息。",
            ["authority.label"] = "控制 daemon 权威端",
            ["retirement_id.label"] = "退役 ID",
            ["bootstrap_id.label"] = "原始 bootstrap ID",
            ["credential.label"] = "SSH 凭证句柄",
            ["a11y.authority"] = "拥有原始 bootstrap 的 daemon 权威端",
            ["a11y.retirement_id"] = "稳定的 daemon 退役操作 ID",
            ["a11y.bootstrap_id"] = "原始 bootstrap 权威 ID",
            ["a11y.credential"] = "不透明 SSH 凭证句柄",
            ["a11y.confirm"] = "确认移除 leserpent daemon",
            ["a11y.submit"] = "退役通过 bootstrap 部署的 daemon 服务",
            ["a11y.refresh"] = "刷新同一次 daemon 退役尝试",
            ["a11y.close"] = "关闭 daemon 退役窗口",
            ["phase.not_submitted"] = "尚未提交",
            ["phase.planned"] = "已规划",
            ["phase.retiring_service"] = "正在退役服务",
            ["phase.service_retired"] = "服务已退役",
            ["phase.failed"] = "失败",
            ["error.confirm_required"] = "提交前请确认退役 daemon。",
            ["error.authority_required"] = "请先选择控制 daemon 权威端。",
            ["status.observation_limit"] = "自动观察已达到受限上限。请使用“刷新同一尝试”检查这个确切的退役 ID，不会创建另一次移除。",
            ["status.waiting"] = "正在等待所选 daemon 权威端...",
            ["status.planned"] = "bootstrap {0} 的退役已持久排队。推导出的目标权威已锁定为 daemon {1}。",
            ["status.retiring_service"] = "控制器正在按检查点推导出的 {1} 配置移除 daemon {0}。",
            ["status.service_retired"] = "daemon {0} 已从 {1}:{2} 退役。请另行移除 Hub 中已经离线的连接。",
            ["status.failed"] = "daemon 退役失败，受限故障代码为 {0}。服务未被标记为已退役；请检查控制器，修复后使用新的退役 ID。",
            ["unavailable"] = "不可用",
        });

    public static IReadOnlyDictionary<string, string> TraditionalChinese { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["title"] = "Leserpent / 退役 daemon",
            ["confirmation"] = "我確認移除此 bootstrap 建立的 leserpentd 服務",
            ["submit"] = "退役 daemon",
            ["refresh"] = "重新整理同一次嘗試",
            ["close"] = "關閉",
            ["status.initial"] = "請選擇執行原始 bootstrap 的 daemon 權威端。",
            ["status.name"] = "Daemon 退役狀態",
            ["phase.name"] = "Daemon 退役階段",
            ["kicker"] = "DAEMON 退役",
            ["heading"] = "移除已 bootstrap 的權威端",
            ["body"] = "控制器會從綁定的 bootstrap 檢查點推導主機、daemon、世代與安裝設定檔。此表單無法覆寫該權威資訊。",
            ["authority.label"] = "控制 daemon 權威端",
            ["retirement_id.label"] = "退役 ID",
            ["bootstrap_id.label"] = "原始 bootstrap ID",
            ["credential.label"] = "SSH 憑證控制代碼",
            ["a11y.authority"] = "擁有原始 bootstrap 的 daemon 權威端",
            ["a11y.retirement_id"] = "穩定的 daemon 退役操作 ID",
            ["a11y.bootstrap_id"] = "原始 bootstrap 權威 ID",
            ["a11y.credential"] = "不透明 SSH 憑證控制代碼",
            ["a11y.confirm"] = "確認移除 leserpent daemon",
            ["a11y.submit"] = "退役透過 bootstrap 部署的 daemon 服務",
            ["a11y.refresh"] = "重新整理同一次 daemon 退役嘗試",
            ["a11y.close"] = "關閉 daemon 退役視窗",
            ["phase.not_submitted"] = "尚未提交",
            ["phase.planned"] = "已規劃",
            ["phase.retiring_service"] = "正在退役服務",
            ["phase.service_retired"] = "服務已退役",
            ["phase.failed"] = "失敗",
            ["error.confirm_required"] = "提交前請確認退役 daemon。",
            ["error.authority_required"] = "請先選擇控制 daemon 權威端。",
            ["status.observation_limit"] = "自動觀察已達受限上限。請使用「重新整理同一次嘗試」檢查這個確切的退役 ID，不會建立另一次移除。",
            ["status.waiting"] = "正在等待所選 daemon 權威端...",
            ["status.planned"] = "bootstrap {0} 的退役已持久排入佇列。推導出的目標權威已鎖定為 daemon {1}。",
            ["status.retiring_service"] = "控制器正在依檢查點推導出的 {1} 設定檔移除 daemon {0}。",
            ["status.service_retired"] = "daemon {0} 已從 {1}:{2} 退役。請另行移除 Hub 中已離線的連線。",
            ["status.failed"] = "daemon 退役失敗，受限故障代碼為 {0}。服務未標記為已退役；請檢查控制器，修復後使用新的退役 ID。",
            ["unavailable"] = "無法使用",
        });

    public static IReadOnlyDictionary<string, string> Japanese { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["title"] = "Leserpent / daemon を廃止",
            ["confirmation"] = "この bootstrap が作成した leserpentd サービスの削除を確認しました",
            ["submit"] = "daemon を廃止",
            ["refresh"] = "同じ試行を更新",
            ["close"] = "閉じる",
            ["status.initial"] = "元の bootstrap を実行した daemon authority を選択してください。",
            ["status.name"] = "Daemon 廃止状態",
            ["phase.name"] = "Daemon 廃止段階",
            ["kicker"] = "DAEMON 廃止",
            ["heading"] = "bootstrap 済み authority を削除",
            ["body"] = "コントローラーは、紐付いた bootstrap チェックポイントからホスト、daemon、世代、インストールプロファイルを導出します。このフォームで authority を上書きすることはできません。",
            ["authority.label"] = "制御 daemon authority",
            ["retirement_id.label"] = "廃止 ID",
            ["bootstrap_id.label"] = "元の bootstrap ID",
            ["credential.label"] = "SSH 認証情報ハンドル",
            ["a11y.authority"] = "元の bootstrap を所有する daemon authority",
            ["a11y.retirement_id"] = "安定した daemon 廃止操作 ID",
            ["a11y.bootstrap_id"] = "元の bootstrap authority ID",
            ["a11y.credential"] = "不透明な SSH 認証情報ハンドル",
            ["a11y.confirm"] = "leserpent daemon の削除を確認",
            ["a11y.submit"] = "bootstrap された daemon サービスを廃止",
            ["a11y.refresh"] = "同じ daemon 廃止試行を更新",
            ["a11y.close"] = "daemon 廃止ウィンドウを閉じる",
            ["phase.not_submitted"] = "未送信",
            ["phase.planned"] = "計画済み",
            ["phase.retiring_service"] = "サービス廃止中",
            ["phase.service_retired"] = "サービス廃止済み",
            ["phase.failed"] = "失敗",
            ["error.confirm_required"] = "送信前に daemon の廃止を確認してください。",
            ["error.authority_required"] = "先に制御 daemon authority を選択してください。",
            ["status.observation_limit"] = "自動観察が上限に達しました。「同じ試行を更新」でこの廃止 ID を調べてください。別の削除は作成されません。",
            ["status.waiting"] = "選択した daemon authority を待機しています...",
            ["status.planned"] = "bootstrap {0} の廃止は永続キューに登録されました。導出された対象 authority は daemon {1} に固定されています。",
            ["status.retiring_service"] = "コントローラーは、チェックポイントから導出した {1} プロファイルで daemon {0} を削除しています。",
            ["status.service_retired"] = "daemon {0} は {1}:{2} から廃止されました。オフラインになった Hub 接続は別途削除してください。",
            ["status.failed"] = "daemon の廃止は制限付き障害 {0} で失敗しました。サービスは廃止済みとして記録されていません。修復後、新しい廃止 ID を使用してください。",
            ["unavailable"] = "利用不可",
        });

    public static IReadOnlyDictionary<string, string> Spanish { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["title"] = "Leserpent / Retirar daemon",
            ["confirmation"] = "Confirmo la eliminación del servicio leserpentd creado por este bootstrap",
            ["submit"] = "Retirar daemon",
            ["refresh"] = "Actualizar el mismo intento",
            ["close"] = "Cerrar",
            ["status.initial"] = "Elige la autoridad daemon que realizó el bootstrap original.",
            ["status.name"] = "Estado de retirada del daemon",
            ["phase.name"] = "Fase de retirada del daemon",
            ["kicker"] = "RETIRADA DEL DAEMON",
            ["heading"] = "Eliminar una autoridad inicializada",
            ["body"] = "El controlador obtiene el host, el daemon, la generación y el perfil de instalación del punto de control de bootstrap vinculado. Este formulario no puede sustituir esa autoridad.",
            ["authority.label"] = "Autoridad daemon de control",
            ["retirement_id.label"] = "ID de retirada",
            ["bootstrap_id.label"] = "ID de bootstrap original",
            ["credential.label"] = "Identificador de credencial SSH",
            ["a11y.authority"] = "Autoridad daemon propietaria del bootstrap original",
            ["a11y.retirement_id"] = "ID estable de la operación de retirada del daemon",
            ["a11y.bootstrap_id"] = "ID de autoridad del bootstrap original",
            ["a11y.credential"] = "Identificador opaco de credencial SSH",
            ["a11y.confirm"] = "Confirmar la eliminación del daemon leserpent",
            ["a11y.submit"] = "Retirar el servicio daemon inicializado",
            ["a11y.refresh"] = "Actualizar el mismo intento de retirada del daemon",
            ["a11y.close"] = "Cerrar la ventana de retirada del daemon",
            ["phase.not_submitted"] = "NO ENVIADO",
            ["phase.planned"] = "PLANIFICADO",
            ["phase.retiring_service"] = "RETIRANDO SERVICIO",
            ["phase.service_retired"] = "SERVICIO RETIRADO",
            ["phase.failed"] = "FALLIDO",
            ["error.confirm_required"] = "Confirma la retirada del daemon antes de enviarla.",
            ["error.authority_required"] = "Selecciona primero la autoridad daemon de control.",
            ["status.observation_limit"] = "La observación automática alcanzó su límite. Usa Actualizar el mismo intento para inspeccionar este ID de retirada exacto sin crear otra eliminación.",
            ["status.waiting"] = "Esperando a la autoridad daemon seleccionada...",
            ["status.planned"] = "La retirada del bootstrap {0} está en la cola duradera. La autoridad de destino derivada está fijada al daemon {1}.",
            ["status.retiring_service"] = "El controlador está eliminando el daemon {0} con el perfil {1} derivado del punto de control.",
            ["status.service_retired"] = "El daemon {0} se retiró de {1}:{2}. Elimina por separado cualquier conexión del Hub que haya quedado sin conexión.",
            ["status.failed"] = "La retirada del daemon falló con el error acotado {0}. El servicio no se marcó como retirado; inspecciona el controlador y usa un nuevo ID tras corregirlo.",
            ["unavailable"] = "no disponible",
        });

    public static IReadOnlyDictionary<string, string> German { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["title"] = "Leserpent / Daemon stilllegen",
            ["confirmation"] = "Ich bestätige das Entfernen des von diesem Bootstrap erstellten leserpentd-Dienstes",
            ["submit"] = "Daemon stilllegen",
            ["refresh"] = "Denselben Versuch aktualisieren",
            ["close"] = "Schließen",
            ["status.initial"] = "Wählen Sie die Daemon-Autorität aus, die den ursprünglichen Bootstrap ausgeführt hat.",
            ["status.name"] = "Status der Daemon-Stilllegung",
            ["phase.name"] = "Phase der Daemon-Stilllegung",
            ["kicker"] = "DAEMON-STILLLEGUNG",
            ["heading"] = "Eine per Bootstrap erstellte Autorität entfernen",
            ["body"] = "Der Controller leitet Host, Daemon, Generation und Installationsprofil vom gebundenen Bootstrap-Prüfpunkt ab. Dieses Formular kann diese Autorität nicht überschreiben.",
            ["authority.label"] = "Steuernde Daemon-Autorität",
            ["retirement_id.label"] = "Stilllegungs-ID",
            ["bootstrap_id.label"] = "Ursprüngliche Bootstrap-ID",
            ["credential.label"] = "SSH-Anmeldeinformationshandle",
            ["a11y.authority"] = "Daemon-Autorität des ursprünglichen Bootstraps",
            ["a11y.retirement_id"] = "Stabile Vorgangs-ID der Daemon-Stilllegung",
            ["a11y.bootstrap_id"] = "Autoritäts-ID des ursprünglichen Bootstraps",
            ["a11y.credential"] = "Opakes SSH-Anmeldeinformationshandle",
            ["a11y.confirm"] = "Entfernen des Leserpent-Daemons bestätigen",
            ["a11y.submit"] = "Den per Bootstrap erstellten Daemon-Dienst stilllegen",
            ["a11y.refresh"] = "Denselben Daemon-Stilllegungsversuch aktualisieren",
            ["a11y.close"] = "Fenster zur Daemon-Stilllegung schließen",
            ["phase.not_submitted"] = "NICHT GESENDET",
            ["phase.planned"] = "GEPLANT",
            ["phase.retiring_service"] = "DIENST WIRD STILLGELEGT",
            ["phase.service_retired"] = "DIENST STILLGELEGT",
            ["phase.failed"] = "FEHLGESCHLAGEN",
            ["error.confirm_required"] = "Bestätigen Sie die Daemon-Stilllegung vor dem Senden.",
            ["error.authority_required"] = "Wählen Sie zuerst die steuernde Daemon-Autorität aus.",
            ["status.observation_limit"] = "Die automatische Beobachtung hat ihr Limit erreicht. Verwenden Sie Denselben Versuch aktualisieren, um genau diese Stilllegungs-ID ohne weitere Entfernung zu prüfen.",
            ["status.waiting"] = "Warten auf die ausgewählte Daemon-Autorität...",
            ["status.planned"] = "Die Stilllegung für Bootstrap {0} ist dauerhaft eingereiht. Die abgeleitete Zielautorität ist auf Daemon {1} festgelegt.",
            ["status.retiring_service"] = "Der Controller entfernt Daemon {0} mit dem aus dem Prüfpunkt abgeleiteten Profil {1}.",
            ["status.service_retired"] = "Daemon {0} wurde von {1}:{2} stillgelegt. Entfernen Sie eine nun getrennte Hub-Verbindung separat.",
            ["status.failed"] = "Die Daemon-Stilllegung ist mit dem begrenzten Fehler {0} fehlgeschlagen. Der Dienst wurde nicht als stillgelegt markiert; prüfen Sie den Controller und verwenden Sie nach der Korrektur eine neue ID.",
            ["unavailable"] = "nicht verfügbar",
        });

    public static IReadOnlyDictionary<string, string> French { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["title"] = "Leserpent / Retirer le daemon",
            ["confirmation"] = "Je confirme la suppression du service leserpentd créé par ce bootstrap",
            ["submit"] = "Retirer le daemon",
            ["refresh"] = "Actualiser la même tentative",
            ["close"] = "Fermer",
            ["status.initial"] = "Choisissez l'autorité daemon qui a effectué le bootstrap initial.",
            ["status.name"] = "État du retrait du daemon",
            ["phase.name"] = "Phase du retrait du daemon",
            ["kicker"] = "RETRAIT DU DAEMON",
            ["heading"] = "Supprimer une autorité initialisée",
            ["body"] = "Le contrôleur déduit l'hôte, le daemon, la génération et le profil d'installation du point de contrôle bootstrap lié. Ce formulaire ne peut pas remplacer cette autorité.",
            ["authority.label"] = "Autorité daemon de contrôle",
            ["retirement_id.label"] = "ID de retrait",
            ["bootstrap_id.label"] = "ID du bootstrap initial",
            ["credential.label"] = "Identifiant d'accréditation SSH",
            ["a11y.authority"] = "Autorité daemon propriétaire du bootstrap initial",
            ["a11y.retirement_id"] = "ID stable de l'opération de retrait du daemon",
            ["a11y.bootstrap_id"] = "ID d'autorité du bootstrap initial",
            ["a11y.credential"] = "Identifiant opaque d'accréditation SSH",
            ["a11y.confirm"] = "Confirmer la suppression du daemon leserpent",
            ["a11y.submit"] = "Retirer le service daemon initialisé",
            ["a11y.refresh"] = "Actualiser la même tentative de retrait du daemon",
            ["a11y.close"] = "Fermer la fenêtre de retrait du daemon",
            ["phase.not_submitted"] = "NON ENVOYÉ",
            ["phase.planned"] = "PLANIFIÉ",
            ["phase.retiring_service"] = "RETRAIT DU SERVICE",
            ["phase.service_retired"] = "SERVICE RETIRÉ",
            ["phase.failed"] = "ÉCHEC",
            ["error.confirm_required"] = "Confirmez le retrait du daemon avant l'envoi.",
            ["error.authority_required"] = "Sélectionnez d'abord l'autorité daemon de contrôle.",
            ["status.observation_limit"] = "L'observation automatique a atteint sa limite. Utilisez Actualiser la même tentative pour examiner cet ID de retrait précis sans créer une autre suppression.",
            ["status.waiting"] = "En attente de l'autorité daemon sélectionnée...",
            ["status.planned"] = "Le retrait du bootstrap {0} est placé dans la file durable. L'autorité cible déduite est verrouillée sur le daemon {1}.",
            ["status.retiring_service"] = "Le contrôleur supprime le daemon {0} avec le profil {1} déduit du point de contrôle.",
            ["status.service_retired"] = "Le daemon {0} a été retiré de {1}:{2}. Supprimez séparément toute connexion Hub désormais hors ligne.",
            ["status.failed"] = "Le retrait du daemon a échoué avec l'erreur bornée {0}. Le service n'a pas été marqué comme retiré ; inspectez le contrôleur et utilisez un nouvel ID après correction.",
            ["unavailable"] = "indisponible",
        });

    public static IReadOnlyDictionary<string, string> Korean { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["title"] = "Leserpent / daemon 폐기",
            ["confirmation"] = "이 bootstrap이 만든 leserpentd 서비스 제거를 확인합니다",
            ["submit"] = "daemon 폐기",
            ["refresh"] = "같은 시도 새로고침",
            ["close"] = "닫기",
            ["status.initial"] = "원래 bootstrap을 수행한 daemon 권한 주체를 선택하세요.",
            ["status.name"] = "Daemon 폐기 상태",
            ["phase.name"] = "Daemon 폐기 단계",
            ["kicker"] = "DAEMON 폐기",
            ["heading"] = "bootstrap된 권한 주체 제거",
            ["body"] = "컨트롤러는 연결된 bootstrap 체크포인트에서 호스트, daemon, 세대 및 설치 프로필을 파생합니다. 이 양식은 해당 권한을 재정의할 수 없습니다.",
            ["authority.label"] = "제어 daemon 권한 주체",
            ["retirement_id.label"] = "폐기 ID",
            ["bootstrap_id.label"] = "원래 bootstrap ID",
            ["credential.label"] = "SSH 자격 증명 핸들",
            ["a11y.authority"] = "원래 bootstrap을 소유한 daemon 권한 주체",
            ["a11y.retirement_id"] = "안정적인 daemon 폐기 작업 ID",
            ["a11y.bootstrap_id"] = "원래 bootstrap 권한 ID",
            ["a11y.credential"] = "불투명한 SSH 자격 증명 핸들",
            ["a11y.confirm"] = "leserpent daemon 제거 확인",
            ["a11y.submit"] = "bootstrap된 daemon 서비스 폐기",
            ["a11y.refresh"] = "같은 daemon 폐기 시도 새로고침",
            ["a11y.close"] = "daemon 폐기 창 닫기",
            ["phase.not_submitted"] = "제출되지 않음",
            ["phase.planned"] = "계획됨",
            ["phase.retiring_service"] = "서비스 폐기 중",
            ["phase.service_retired"] = "서비스 폐기됨",
            ["phase.failed"] = "실패",
            ["error.confirm_required"] = "제출하기 전에 daemon 폐기를 확인하세요.",
            ["error.authority_required"] = "먼저 제어 daemon 권한 주체를 선택하세요.",
            ["status.observation_limit"] = "자동 관찰이 제한에 도달했습니다. 다른 제거를 만들지 않고 이 폐기 ID를 확인하려면 ‘같은 시도 새로고침’을 사용하세요.",
            ["status.waiting"] = "선택한 daemon 권한 주체를 기다리는 중...",
            ["status.planned"] = "bootstrap {0}의 폐기 작업이 영구 큐에 등록되었습니다. 파생된 대상 권한은 daemon {1}에 고정됩니다.",
            ["status.retiring_service"] = "컨트롤러가 체크포인트에서 파생된 {1} 프로필로 daemon {0}을 제거하고 있습니다.",
            ["status.service_retired"] = "daemon {0}이(가) {1}:{2}에서 폐기되었습니다. 오프라인이 된 Hub 연결은 별도로 제거하세요.",
            ["status.failed"] = "제한된 오류 {0}(으)로 daemon 폐기에 실패했습니다. 서비스는 폐기된 것으로 표시되지 않았습니다. 수정 후 새 폐기 ID를 사용하세요.",
            ["unavailable"] = "사용할 수 없음",
        });

    public static string Resolve(DesktopLocalization localization, string key)
    {
        var fullKey = FullKey(key);
        return localization.Resolve(new LocalizedText
        {
            Key = fullKey,
            Fallback = English[fullKey],
        });
    }

    public static string Format(
        DesktopLocalization localization,
        string key,
        params object[] values) => string.Format(
            CultureInfo.InvariantCulture,
            Resolve(localization, key),
            values);

    public static void VerifyContract() => DesktopDomainCatalogContract.Verify(
        "daemon retirement",
        KeyCount,
        All,
        new Dictionary<string, int>(StringComparer.Ordinal)
        {
            [FullKey("status.planned")] = 2,
            [FullKey("status.retiring_service")] = 2,
            [FullKey("status.service_retired")] = 3,
            [FullKey("status.failed")] = 1,
        });

    private static IReadOnlyList<IReadOnlyDictionary<string, string>> All =>
        [English, SimplifiedChinese, TraditionalChinese, Japanese, Spanish, German, French, Korean];

    private static IReadOnlyDictionary<string, string> Catalog(
        Dictionary<string, string> values) =>
        DesktopDomainCatalogContract.Catalog(Prefix, values);

    private static string FullKey(string key) => $"{Prefix}{key}";
}
