using System.Globalization;

internal static class DesktopAccountCatalogs
{
    private const string Prefix = "desktop.account.";
    public const int KeyCount = 37;

    public static IReadOnlyDictionary<string, string> English { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["label"] = "TEAM SILVORTEX",
            ["access.core"] = "Core tools are MIT-licensed, open source, and free. Accounts are only for future hosted subscription services and never replace daemon credentials.",
            ["identity.disabled"] = "Offline workspace",
            ["identity.signed_out"] = "No account session",
            ["identity.working"] = "Securing session...",
            ["identity.authenticated"] = "Authenticated account",
            ["identity.error"] = "Account needs attention",
            ["identity.unavailable"] = "Account unavailable",
            ["action.disabled"] = "Not configured",
            ["action.working"] = "Working...",
            ["action.signed_in"] = "Sign out",
            ["action.error"] = "Retry",
            ["action.signed_out"] = "Sign in",
            ["a11y.status"] = "Team Silvortex account status: {0}. {1}",
            ["a11y.sign_out"] = "Sign out of Team Silvortex in Leserpent",
            ["a11y.sign_in"] = "Sign in to Team Silvortex",
            ["a11y.help"] = "Uses the system browser and a protected local PKCE callback. Daemon credentials remain separate.",
            ["status.configuration_invalid"] = "Team Silvortex account configuration is invalid: {0}",
            ["status.override_refused"] = "Packaged Team Silvortex configuration refuses environment overrides.",
            ["status.optional_bundle"] = "Team Silvortex sign-in is optional and is not configured in this application bundle.",
            ["status.bundle_ready"] = "Team Silvortex sign-in is ready from the application bundle.",
            ["status.optional_build"] = "Team Silvortex sign-in is optional and is not configured for this build.",
            ["status.missing_issuer"] = "Set {0} when configuring Team Silvortex sign-in.",
            ["status.development_ready"] = "Team Silvortex sign-in is ready from development configuration.",
            ["status.verification_disabled"] = "Team Silvortex sign-in is not configured for verification.",
            ["status.proof_ready"] = "Team Silvortex desktop proof is ready.",
            ["status.opening_browser"] = "Opening the secure Team Silvortex sign-in page...",
            ["status.awaiting_callback"] = "Complete sign-in in your browser. Leserpent is waiting for the local callback.",
            ["status.sign_in_failed"] = "Sign-in failed: {0}",
            ["status.signing_out"] = "Signing out of Leserpent...",
            ["status.signed_out"] = "Signed out locally. Daemon connections and offline control remain available.",
            ["status.sign_out_failed"] = "Sign-out could not clear the secure session: {0}",
            ["status.sign_in_required"] = "Sign in to connect this desktop client to your Team Silvortex account.",
            ["status.restoring"] = "Restoring the protected Team Silvortex session...",
            ["status.restore_failed"] = "The saved account session could not be restored: {0}",
            ["status.authenticated"] = "Authenticated with MFA. Daemon credentials remain independently scoped.",
            ["status.raw"] = "{0}",
        });

    public static IReadOnlyDictionary<string, string> SimplifiedChinese { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["label"] = "TEAM SILVORTEX",
            ["access.core"] = "核心功能采用 MIT 许可证、开源且免费；账号仅用于未来的托管订阅服务，且不能替代 daemon 凭证。",
            ["identity.disabled"] = "离线工作区",
            ["identity.signed_out"] = "没有账号会话",
            ["identity.working"] = "正在保护会话...",
            ["identity.authenticated"] = "已认证账号",
            ["identity.error"] = "账号需要处理",
            ["identity.unavailable"] = "账号不可用",
            ["action.disabled"] = "未配置",
            ["action.working"] = "处理中...",
            ["action.signed_in"] = "退出登录",
            ["action.error"] = "重试",
            ["action.signed_out"] = "登录",
            ["a11y.status"] = "Team Silvortex 账号状态：{0}。{1}",
            ["a11y.sign_out"] = "在 Leserpent 中退出 Team Silvortex",
            ["a11y.sign_in"] = "登录 Team Silvortex",
            ["a11y.help"] = "使用系统浏览器和受保护的本地 PKCE 回调。Daemon 凭证保持独立。",
            ["status.configuration_invalid"] = "Team Silvortex 账号配置无效：{0}",
            ["status.override_refused"] = "打包的 Team Silvortex 配置拒绝环境变量覆盖。",
            ["status.optional_bundle"] = "Team Silvortex 登录是可选功能，此应用包尚未配置。",
            ["status.bundle_ready"] = "Team Silvortex 登录已通过应用包配置就绪。",
            ["status.optional_build"] = "Team Silvortex 登录是可选功能，此构建尚未配置。",
            ["status.missing_issuer"] = "配置 Team Silvortex 登录时请设置 {0}。",
            ["status.development_ready"] = "Team Silvortex 登录已通过开发配置就绪。",
            ["status.verification_disabled"] = "验证环境未配置 Team Silvortex 登录。",
            ["status.proof_ready"] = "Team Silvortex 桌面证明已就绪。",
            ["status.opening_browser"] = "正在打开安全的 Team Silvortex 登录页面...",
            ["status.awaiting_callback"] = "请在浏览器中完成登录。Leserpent 正在等待本地回调。",
            ["status.sign_in_failed"] = "登录失败：{0}",
            ["status.signing_out"] = "正在退出 Leserpent...",
            ["status.signed_out"] = "已在本地退出。Daemon 连接和离线控制仍然可用。",
            ["status.sign_out_failed"] = "退出登录时无法清除安全会话：{0}",
            ["status.sign_in_required"] = "登录即可将此桌面客户端连接到 Team Silvortex 账号。",
            ["status.restoring"] = "正在恢复受保护的 Team Silvortex 会话...",
            ["status.restore_failed"] = "无法恢复已保存的账号会话：{0}",
            ["status.authenticated"] = "已通过 MFA 认证。Daemon 凭证仍保持独立作用域。",
            ["status.raw"] = "{0}",
        });

    public static IReadOnlyDictionary<string, string> TraditionalChinese { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["label"] = "TEAM SILVORTEX",
            ["access.core"] = "核心功能採用 MIT 授權、開源且免費；帳號僅用於未來的託管訂閱服務，且不能取代 daemon 憑證。",
            ["identity.disabled"] = "離線工作區",
            ["identity.signed_out"] = "沒有帳號工作階段",
            ["identity.working"] = "正在保護工作階段...",
            ["identity.authenticated"] = "已驗證帳號",
            ["identity.error"] = "帳號需要處理",
            ["identity.unavailable"] = "帳號無法使用",
            ["action.disabled"] = "未設定",
            ["action.working"] = "處理中...",
            ["action.signed_in"] = "登出",
            ["action.error"] = "重試",
            ["action.signed_out"] = "登入",
            ["a11y.status"] = "Team Silvortex 帳號狀態：{0}。{1}",
            ["a11y.sign_out"] = "在 Leserpent 中登出 Team Silvortex",
            ["a11y.sign_in"] = "登入 Team Silvortex",
            ["a11y.help"] = "使用系統瀏覽器和受保護的本機 PKCE 回呼。Daemon 憑證保持獨立。",
            ["status.configuration_invalid"] = "Team Silvortex 帳號設定無效：{0}",
            ["status.override_refused"] = "封裝的 Team Silvortex 設定拒絕環境變數覆寫。",
            ["status.optional_bundle"] = "Team Silvortex 登入是選用功能，此應用程式套件尚未設定。",
            ["status.bundle_ready"] = "Team Silvortex 登入已透過應用程式套件設定完成。",
            ["status.optional_build"] = "Team Silvortex 登入是選用功能，此組建尚未設定。",
            ["status.missing_issuer"] = "設定 Team Silvortex 登入時請設定 {0}。",
            ["status.development_ready"] = "Team Silvortex 登入已透過開發設定完成。",
            ["status.verification_disabled"] = "驗證環境未設定 Team Silvortex 登入。",
            ["status.proof_ready"] = "Team Silvortex 桌面證明已就緒。",
            ["status.opening_browser"] = "正在開啟安全的 Team Silvortex 登入頁面...",
            ["status.awaiting_callback"] = "請在瀏覽器中完成登入。Leserpent 正在等待本機回呼。",
            ["status.sign_in_failed"] = "登入失敗：{0}",
            ["status.signing_out"] = "正在登出 Leserpent...",
            ["status.signed_out"] = "已在本機登出。Daemon 連線與離線控制仍然可用。",
            ["status.sign_out_failed"] = "登出時無法清除安全工作階段：{0}",
            ["status.sign_in_required"] = "登入即可將此桌面用戶端連線至 Team Silvortex 帳號。",
            ["status.restoring"] = "正在還原受保護的 Team Silvortex 工作階段...",
            ["status.restore_failed"] = "無法還原已儲存的帳號工作階段：{0}",
            ["status.authenticated"] = "已透過 MFA 驗證。Daemon 憑證仍保持獨立範圍。",
            ["status.raw"] = "{0}",
        });

    public static IReadOnlyDictionary<string, string> Japanese { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["label"] = "TEAM SILVORTEX",
            ["access.core"] = "コア機能は MIT ライセンスのオープンソースで無料です。アカウントは将来のホスト型サブスクリプションサービス専用で、daemon 認証情報の代わりにはなりません。",
            ["identity.disabled"] = "オフラインワークスペース",
            ["identity.signed_out"] = "アカウントセッションなし",
            ["identity.working"] = "セッションを保護しています...",
            ["identity.authenticated"] = "認証済みアカウント",
            ["identity.error"] = "アカウントの確認が必要です",
            ["identity.unavailable"] = "アカウントを利用できません",
            ["action.disabled"] = "未設定",
            ["action.working"] = "処理中...",
            ["action.signed_in"] = "サインアウト",
            ["action.error"] = "再試行",
            ["action.signed_out"] = "サインイン",
            ["a11y.status"] = "Team Silvortex アカウント状態: {0}。{1}",
            ["a11y.sign_out"] = "Leserpent で Team Silvortex からサインアウト",
            ["a11y.sign_in"] = "Team Silvortex にサインイン",
            ["a11y.help"] = "システムブラウザーと保護されたローカル PKCE コールバックを使用します。Daemon 認証情報は分離されたままです。",
            ["status.configuration_invalid"] = "Team Silvortex アカウント設定が無効です: {0}",
            ["status.override_refused"] = "パッケージ化された Team Silvortex 設定は環境変数による上書きを拒否します。",
            ["status.optional_bundle"] = "Team Silvortex サインインは任意で、このアプリケーションバンドルには設定されていません。",
            ["status.bundle_ready"] = "Team Silvortex サインインはアプリケーションバンドルから利用できます。",
            ["status.optional_build"] = "Team Silvortex サインインは任意で、このビルドには設定されていません。",
            ["status.missing_issuer"] = "Team Silvortex サインインを設定するときは {0} を指定してください。",
            ["status.development_ready"] = "Team Silvortex サインインは開発設定から利用できます。",
            ["status.verification_disabled"] = "検証環境には Team Silvortex サインインが設定されていません。",
            ["status.proof_ready"] = "Team Silvortex デスクトップ証明の準備ができました。",
            ["status.opening_browser"] = "安全な Team Silvortex サインインページを開いています...",
            ["status.awaiting_callback"] = "ブラウザーでサインインを完了してください。Leserpent はローカルコールバックを待機しています。",
            ["status.sign_in_failed"] = "サインインに失敗しました: {0}",
            ["status.signing_out"] = "Leserpent からサインアウトしています...",
            ["status.signed_out"] = "ローカルでサインアウトしました。Daemon 接続とオフライン制御は引き続き利用できます。",
            ["status.sign_out_failed"] = "サインアウト時に安全なセッションを消去できませんでした: {0}",
            ["status.sign_in_required"] = "このデスクトップクライアントを Team Silvortex アカウントに接続するにはサインインしてください。",
            ["status.restoring"] = "保護された Team Silvortex セッションを復元しています...",
            ["status.restore_failed"] = "保存済みアカウントセッションを復元できませんでした: {0}",
            ["status.authenticated"] = "MFA で認証済みです。Daemon 認証情報のスコープは独立したままです。",
            ["status.raw"] = "{0}",
        });

    public static IReadOnlyDictionary<string, string> Spanish { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["label"] = "TEAM SILVORTEX",
            ["access.core"] = "Las funciones principales usan licencia MIT, son de código abierto y gratuitas. La cuenta solo sirve para futuros servicios alojados por suscripción y nunca sustituye las credenciales del daemon.",
            ["identity.disabled"] = "Espacio de trabajo sin conexión",
            ["identity.signed_out"] = "Sin sesión de cuenta",
            ["identity.working"] = "Protegiendo la sesión...",
            ["identity.authenticated"] = "Cuenta autenticada",
            ["identity.error"] = "La cuenta necesita atención",
            ["identity.unavailable"] = "Cuenta no disponible",
            ["action.disabled"] = "Sin configurar",
            ["action.working"] = "Procesando...",
            ["action.signed_in"] = "Cerrar sesión",
            ["action.error"] = "Reintentar",
            ["action.signed_out"] = "Iniciar sesión",
            ["a11y.status"] = "Estado de la cuenta de Team Silvortex: {0}. {1}",
            ["a11y.sign_out"] = "Cerrar la sesión de Team Silvortex en Leserpent",
            ["a11y.sign_in"] = "Iniciar sesión en Team Silvortex",
            ["a11y.help"] = "Usa el navegador del sistema y una devolución de llamada PKCE local protegida. Las credenciales del daemon permanecen separadas.",
            ["status.configuration_invalid"] = "La configuración de la cuenta de Team Silvortex no es válida: {0}",
            ["status.override_refused"] = "La configuración empaquetada de Team Silvortex rechaza las sustituciones del entorno.",
            ["status.optional_bundle"] = "El inicio de sesión de Team Silvortex es opcional y no está configurado en este paquete.",
            ["status.bundle_ready"] = "El inicio de sesión de Team Silvortex está listo desde el paquete de la aplicación.",
            ["status.optional_build"] = "El inicio de sesión de Team Silvortex es opcional y no está configurado para esta compilación.",
            ["status.missing_issuer"] = "Configura {0} al habilitar el inicio de sesión de Team Silvortex.",
            ["status.development_ready"] = "El inicio de sesión de Team Silvortex está listo desde la configuración de desarrollo.",
            ["status.verification_disabled"] = "El inicio de sesión de Team Silvortex no está configurado para la verificación.",
            ["status.proof_ready"] = "La prueba de escritorio de Team Silvortex está lista.",
            ["status.opening_browser"] = "Abriendo la página segura de inicio de sesión de Team Silvortex...",
            ["status.awaiting_callback"] = "Completa el inicio de sesión en el navegador. Leserpent espera la devolución de llamada local.",
            ["status.sign_in_failed"] = "Error al iniciar sesión: {0}",
            ["status.signing_out"] = "Cerrando la sesión de Leserpent...",
            ["status.signed_out"] = "Sesión cerrada localmente. Las conexiones daemon y el control sin conexión siguen disponibles.",
            ["status.sign_out_failed"] = "No se pudo borrar la sesión segura al cerrar sesión: {0}",
            ["status.sign_in_required"] = "Inicia sesión para conectar este cliente de escritorio con tu cuenta de Team Silvortex.",
            ["status.restoring"] = "Restaurando la sesión protegida de Team Silvortex...",
            ["status.restore_failed"] = "No se pudo restaurar la sesión de cuenta guardada: {0}",
            ["status.authenticated"] = "Autenticación con MFA completada. Las credenciales del daemon mantienen un ámbito independiente.",
            ["status.raw"] = "{0}",
        });

    public static IReadOnlyDictionary<string, string> German { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["label"] = "TEAM SILVORTEX",
            ["access.core"] = "Die Kernfunktionen sind MIT-lizenziert, quelloffen und kostenlos. Das Konto dient nur künftigen gehosteten Abonnementdiensten und ersetzt niemals Daemon-Anmeldedaten.",
            ["identity.disabled"] = "Offline-Arbeitsbereich",
            ["identity.signed_out"] = "Keine Kontositzung",
            ["identity.working"] = "Sitzung wird geschützt...",
            ["identity.authenticated"] = "Authentifiziertes Konto",
            ["identity.error"] = "Konto erfordert Aufmerksamkeit",
            ["identity.unavailable"] = "Konto nicht verfügbar",
            ["action.disabled"] = "Nicht konfiguriert",
            ["action.working"] = "Wird verarbeitet...",
            ["action.signed_in"] = "Abmelden",
            ["action.error"] = "Wiederholen",
            ["action.signed_out"] = "Anmelden",
            ["a11y.status"] = "Team-Silvortex-Kontostatus: {0}. {1}",
            ["a11y.sign_out"] = "In Leserpent von Team Silvortex abmelden",
            ["a11y.sign_in"] = "Bei Team Silvortex anmelden",
            ["a11y.help"] = "Verwendet den Systembrowser und einen geschützten lokalen PKCE-Rückruf. Daemon-Anmeldeinformationen bleiben getrennt.",
            ["status.configuration_invalid"] = "Die Team-Silvortex-Kontokonfiguration ist ungültig: {0}",
            ["status.override_refused"] = "Die paketierte Team-Silvortex-Konfiguration lehnt Umgebungsüberschreibungen ab.",
            ["status.optional_bundle"] = "Die Team-Silvortex-Anmeldung ist optional und in diesem Anwendungspaket nicht konfiguriert.",
            ["status.bundle_ready"] = "Die Team-Silvortex-Anmeldung ist aus dem Anwendungspaket verfügbar.",
            ["status.optional_build"] = "Die Team-Silvortex-Anmeldung ist optional und für diesen Build nicht konfiguriert.",
            ["status.missing_issuer"] = "Legen Sie {0} beim Konfigurieren der Team-Silvortex-Anmeldung fest.",
            ["status.development_ready"] = "Die Team-Silvortex-Anmeldung ist aus der Entwicklungskonfiguration verfügbar.",
            ["status.verification_disabled"] = "Die Team-Silvortex-Anmeldung ist für die Überprüfung nicht konfiguriert.",
            ["status.proof_ready"] = "Der Team-Silvortex-Desktopnachweis ist bereit.",
            ["status.opening_browser"] = "Die sichere Team-Silvortex-Anmeldeseite wird geöffnet...",
            ["status.awaiting_callback"] = "Schließen Sie die Anmeldung im Browser ab. Leserpent wartet auf den lokalen Rückruf.",
            ["status.sign_in_failed"] = "Anmeldung fehlgeschlagen: {0}",
            ["status.signing_out"] = "Abmeldung von Leserpent...",
            ["status.signed_out"] = "Lokal abgemeldet. Daemon-Verbindungen und Offlinesteuerung bleiben verfügbar.",
            ["status.sign_out_failed"] = "Die sichere Sitzung konnte beim Abmelden nicht gelöscht werden: {0}",
            ["status.sign_in_required"] = "Melden Sie sich an, um diesen Desktopclient mit Ihrem Team-Silvortex-Konto zu verbinden.",
            ["status.restoring"] = "Die geschützte Team-Silvortex-Sitzung wird wiederhergestellt...",
            ["status.restore_failed"] = "Die gespeicherte Kontositzung konnte nicht wiederhergestellt werden: {0}",
            ["status.authenticated"] = "Mit MFA authentifiziert. Daemon-Anmeldeinformationen bleiben unabhängig begrenzt.",
            ["status.raw"] = "{0}",
        });

    public static IReadOnlyDictionary<string, string> French { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["label"] = "TEAM SILVORTEX",
            ["access.core"] = "Les fonctions principales sont sous licence MIT, open source et gratuites. Le compte sert uniquement aux futurs services hébergés sur abonnement et ne remplace jamais les identifiants du daemon.",
            ["identity.disabled"] = "Espace de travail hors ligne",
            ["identity.signed_out"] = "Aucune session de compte",
            ["identity.working"] = "Sécurisation de la session...",
            ["identity.authenticated"] = "Compte authentifié",
            ["identity.error"] = "Le compte nécessite votre attention",
            ["identity.unavailable"] = "Compte indisponible",
            ["action.disabled"] = "Non configuré",
            ["action.working"] = "Traitement...",
            ["action.signed_in"] = "Se déconnecter",
            ["action.error"] = "Réessayer",
            ["action.signed_out"] = "Se connecter",
            ["a11y.status"] = "État du compte Team Silvortex : {0}. {1}",
            ["a11y.sign_out"] = "Se déconnecter de Team Silvortex dans Leserpent",
            ["a11y.sign_in"] = "Se connecter à Team Silvortex",
            ["a11y.help"] = "Utilise le navigateur système et un rappel PKCE local protégé. Les accréditations du daemon restent séparées.",
            ["status.configuration_invalid"] = "La configuration du compte Team Silvortex est invalide : {0}",
            ["status.override_refused"] = "La configuration Team Silvortex du paquet refuse les remplacements par l'environnement.",
            ["status.optional_bundle"] = "La connexion Team Silvortex est facultative et n'est pas configurée dans ce paquet d'application.",
            ["status.bundle_ready"] = "La connexion Team Silvortex est prête depuis le paquet de l'application.",
            ["status.optional_build"] = "La connexion Team Silvortex est facultative et n'est pas configurée pour cette version.",
            ["status.missing_issuer"] = "Définissez {0} lors de la configuration de la connexion Team Silvortex.",
            ["status.development_ready"] = "La connexion Team Silvortex est prête depuis la configuration de développement.",
            ["status.verification_disabled"] = "La connexion Team Silvortex n'est pas configurée pour la vérification.",
            ["status.proof_ready"] = "La preuve de bureau Team Silvortex est prête.",
            ["status.opening_browser"] = "Ouverture de la page de connexion sécurisée Team Silvortex...",
            ["status.awaiting_callback"] = "Terminez la connexion dans votre navigateur. Leserpent attend le rappel local.",
            ["status.sign_in_failed"] = "Échec de la connexion : {0}",
            ["status.signing_out"] = "Déconnexion de Leserpent...",
            ["status.signed_out"] = "Déconnexion locale terminée. Les connexions daemon et le contrôle hors ligne restent disponibles.",
            ["status.sign_out_failed"] = "La session sécurisée n'a pas pu être effacée lors de la déconnexion : {0}",
            ["status.sign_in_required"] = "Connectez-vous pour associer ce client de bureau à votre compte Team Silvortex.",
            ["status.restoring"] = "Restauration de la session Team Silvortex protégée...",
            ["status.restore_failed"] = "La session de compte enregistrée n'a pas pu être restaurée : {0}",
            ["status.authenticated"] = "Authentification MFA réussie. Les accréditations du daemon gardent une portée indépendante.",
            ["status.raw"] = "{0}",
        });

    public static IReadOnlyDictionary<string, string> Korean { get; } = Catalog(
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["label"] = "TEAM SILVORTEX",
            ["access.core"] = "핵심 기능은 MIT 라이선스의 오픈 소스이며 무료입니다. 계정은 향후 호스팅 구독 서비스에만 사용되며 daemon 자격 증명을 대체하지 않습니다.",
            ["identity.disabled"] = "오프라인 작업 공간",
            ["identity.signed_out"] = "계정 세션 없음",
            ["identity.working"] = "세션 보호 중...",
            ["identity.authenticated"] = "인증된 계정",
            ["identity.error"] = "계정 확인 필요",
            ["identity.unavailable"] = "계정을 사용할 수 없음",
            ["action.disabled"] = "구성되지 않음",
            ["action.working"] = "처리 중...",
            ["action.signed_in"] = "로그아웃",
            ["action.error"] = "다시 시도",
            ["action.signed_out"] = "로그인",
            ["a11y.status"] = "Team Silvortex 계정 상태: {0}. {1}",
            ["a11y.sign_out"] = "Leserpent에서 Team Silvortex 로그아웃",
            ["a11y.sign_in"] = "Team Silvortex 로그인",
            ["a11y.help"] = "시스템 브라우저와 보호된 로컬 PKCE 콜백을 사용합니다. Daemon 자격 증명은 분리된 상태로 유지됩니다.",
            ["status.configuration_invalid"] = "Team Silvortex 계정 구성이 잘못되었습니다: {0}",
            ["status.override_refused"] = "패키지된 Team Silvortex 구성은 환경 재정의를 거부합니다.",
            ["status.optional_bundle"] = "Team Silvortex 로그인은 선택 사항이며 이 앱 번들에는 구성되어 있지 않습니다.",
            ["status.bundle_ready"] = "Team Silvortex 로그인이 앱 번들 구성으로 준비되었습니다.",
            ["status.optional_build"] = "Team Silvortex 로그인은 선택 사항이며 이 빌드에는 구성되어 있지 않습니다.",
            ["status.missing_issuer"] = "Team Silvortex 로그인을 구성할 때 {0}을(를) 설정하세요.",
            ["status.development_ready"] = "Team Silvortex 로그인이 개발 구성으로 준비되었습니다.",
            ["status.verification_disabled"] = "검증 환경에는 Team Silvortex 로그인이 구성되어 있지 않습니다.",
            ["status.proof_ready"] = "Team Silvortex 데스크톱 증명이 준비되었습니다.",
            ["status.opening_browser"] = "안전한 Team Silvortex 로그인 페이지를 여는 중...",
            ["status.awaiting_callback"] = "브라우저에서 로그인을 완료하세요. Leserpent가 로컬 콜백을 기다리고 있습니다.",
            ["status.sign_in_failed"] = "로그인 실패: {0}",
            ["status.signing_out"] = "Leserpent에서 로그아웃하는 중...",
            ["status.signed_out"] = "로컬에서 로그아웃했습니다. Daemon 연결과 오프라인 제어는 계속 사용할 수 있습니다.",
            ["status.sign_out_failed"] = "로그아웃 중 보안 세션을 지울 수 없습니다: {0}",
            ["status.sign_in_required"] = "이 데스크톱 클라이언트를 Team Silvortex 계정에 연결하려면 로그인하세요.",
            ["status.restoring"] = "보호된 Team Silvortex 세션을 복원하는 중...",
            ["status.restore_failed"] = "저장된 계정 세션을 복원할 수 없습니다: {0}",
            ["status.authenticated"] = "MFA로 인증되었습니다. Daemon 자격 증명은 독립된 범위를 유지합니다.",
            ["status.raw"] = "{0}",
        });

    public static string Resolve(DesktopLocalization localization, string key)
    {
        var fullKey = FullKey(key);
        return localization.Resolve(new LocalizedText
        {
            Key = fullKey,
            Fallback = English[fullKey],
        });
    }

    public static string Format(
        DesktopLocalization localization,
        string key,
        params object[] values) => string.Format(
            CultureInfo.InvariantCulture,
            Resolve(localization, key),
            values);

    public static void VerifyContract() => DesktopDomainCatalogContract.Verify(
        "account",
        KeyCount,
        All,
        new Dictionary<string, int>(StringComparer.Ordinal)
        {
            [FullKey("a11y.status")] = 2,
            [FullKey("status.configuration_invalid")] = 1,
            [FullKey("status.missing_issuer")] = 1,
            [FullKey("status.sign_in_failed")] = 1,
            [FullKey("status.sign_out_failed")] = 1,
            [FullKey("status.restore_failed")] = 1,
            [FullKey("status.raw")] = 1,
        });

    private static IReadOnlyList<IReadOnlyDictionary<string, string>> All =>
        [English, SimplifiedChinese, TraditionalChinese, Japanese, Spanish, German, French, Korean];

    private static IReadOnlyDictionary<string, string> Catalog(
        Dictionary<string, string> values) =>
        DesktopDomainCatalogContract.Catalog(Prefix, values);

    private static string FullKey(string key) => $"{Prefix}{key}";
}
