using Avalonia;
using Avalonia.Automation;
using Avalonia.Controls;
using Avalonia.Input.Platform;
using Avalonia.Media;

internal sealed class LeselangExportControl : StackPanel
{
    private static readonly TimeSpan ExportDebounce = TimeSpan.FromMilliseconds(160);
    private readonly Button copy;
    private readonly TextBox preview;
    private readonly TextBlock status;
    private CancellationTokenSource? exportRequest;

    public LeselangExportControl(
        string automationPrefix,
        Func<CancellationToken, Task<string>>? sourceLoader = null)
    {
        Spacing = 8;
        preview = new TextBox
        {
            AcceptsReturn = true,
            IsReadOnly = true,
            FontFamily = new FontFamily("JetBrains Mono, Menlo, monospace"),
            FontSize = 12,
            MaxHeight = 150,
            TextWrapping = TextWrapping.Wrap,
        };
        copy = new Button
        {
            Content = "Copy Leselang",
            HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Left,
            Padding = new Thickness(14, 7),
        };
        status = new TextBlock
        {
            Foreground = LeserpentTheme.Muted,
            FontSize = 12,
            TextWrapping = TextWrapping.Wrap,
        };
        AutomationProperties.SetAutomationId(
            preview,
            $"{automationPrefix}-leselang-preview");
        AutomationProperties.SetName(preview, "Equivalent Leselang source");
        AutomationProperties.SetAutomationId(
            copy,
            $"{automationPrefix}-leselang-copy");
        AutomationProperties.SetName(copy, "Copy equivalent Leselang source");
        AutomationProperties.SetHelpText(
            copy,
            "Copies the code-equivalent operation without executing it.");
        AutomationProperties.SetAutomationId(
            status,
            $"{automationPrefix}-leselang-copy-status");
        AutomationProperties.SetName(status, "Leselang copy status");
        AutomationProperties.SetLiveSetting(status, AutomationLiveSetting.Polite);
        copy.Click += async (_, _) => await CopyAsync();
        Children.Add(new TextBlock
        {
            Text = "Equivalent Leselang",
            Foreground = LeserpentTheme.Body,
            FontWeight = FontWeight.SemiBold,
        });
        Children.Add(preview);
        Children.Add(copy);
        Children.Add(status);
        DetachedFromVisualTree += (_, _) => CancelExport();
        Update(sourceLoader);
    }

    public void Update(Func<CancellationToken, Task<string>>? sourceLoader)
    {
        exportRequest?.Cancel();
        exportRequest?.Dispose();
        exportRequest = null;
        preview.Text = string.Empty;
        copy.IsEnabled = false;
        if (sourceLoader is null)
        {
            SetStatus("Enter valid values to generate equivalent Leselang.", false);
            return;
        }
        var request = new CancellationTokenSource();
        exportRequest = request;
        SetStatus("Generating canonical Leselang from the Rust core...", false);
        _ = LoadAsync(sourceLoader, request);
    }

    private async Task LoadAsync(
        Func<CancellationToken, Task<string>> sourceLoader,
        CancellationTokenSource request)
    {
        try
        {
            await Task.Delay(ExportDebounce, request.Token);
            var source = await sourceLoader(request.Token);
            if (!ReferenceEquals(exportRequest, request) || request.IsCancellationRequested)
            {
                return;
            }
            preview.Text = source;
            copy.IsEnabled = !string.IsNullOrEmpty(source);
            SetStatus("Canonical source generated by the connected Rust core.", false);
        }
        catch (OperationCanceledException) when (request.IsCancellationRequested)
        {
        }
        catch (Exception) when (!request.IsCancellationRequested)
        {
            if (ReferenceEquals(exportRequest, request))
            {
                preview.Text = string.Empty;
                copy.IsEnabled = false;
                SetStatus(
                    "Canonical Leselang unavailable; no local template was substituted.",
                    true);
            }
        }
        finally
        {
            if (ReferenceEquals(exportRequest, request))
            {
                exportRequest = null;
                request.Dispose();
            }
        }
    }

    private void CancelExport()
    {
        exportRequest?.Cancel();
        exportRequest?.Dispose();
        exportRequest = null;
    }

    private async Task CopyAsync()
    {
        var source = preview.Text;
        var clipboard = TopLevel.GetTopLevel(this)?.Clipboard;
        if (string.IsNullOrEmpty(source) || clipboard is null)
        {
            SetStatus("Clipboard unavailable.", true);
            return;
        }
        try
        {
            await clipboard.SetTextAsync(source);
            SetStatus("Leselang copied. No operation was executed.", false);
        }
        catch (Exception)
        {
            SetStatus("Leselang copy failed safely.", true);
        }
    }

    private void SetStatus(string value, bool failed)
    {
        status.Text = value;
        status.Foreground = failed
            ? LeserpentTheme.Destructive
            : LeserpentTheme.Accent;
        AutomationProperties.SetName(status, value);
        AutomationProperties.SetLiveSetting(
            status,
            failed ? AutomationLiveSetting.Assertive : AutomationLiveSetting.Polite);
    }
}
